<?php
declare(strict_types=1);

function site_page_definitions(): array
{
    static $definitions;

    if ($definitions !== null) {
        return $definitions;
    }

    $definitions = [
        '404' => [
            'slug' => '404',
            'path' => '/404.php',
            'nav_key' => '',
            'template' => '404',
            'title' => 'Page Not Found | Bald Eagle Network Services',
            'description' => 'The page you requested was not found.',
            'hero_kicker' => '404',
            'hero_title' => 'That page does not exist or is no longer available.',
            'hero_intro' => 'Return to the main site, review services, or send a request if you were looking for support, project help, or a security review.',
            'robots' => 'noindex,follow',
        ],
        'about' => [
            'slug' => 'about',
            'path' => '/about',
            'nav_key' => 'about',
            'template' => 'about',
            'title' => 'About Bald Eagle Network Services | Recovery-First Operations in Utah',
            'description' => 'Learn how Steve Carlsen handles recovery-first operations directly for small businesses in Utah without outsourcing or ticket-routing layers.',
            'hero_kicker' => 'About Bald Eagle',
            'hero_title' => 'Security-Enforced Recovery, Handled Directly',
            'hero_intro' => 'Bald Eagle Network Services is Steve Carlsen\'s operator-led recovery business for small companies that need direct accountability, practical security, and dependable day-to-day system continuity without outsourcing or ticket-routing layers.',
            'schema_person' => [
                'name' => 'Steve Carlsen',
                'jobTitle' => 'Founder and Operator',
                'description' => 'Steve Carlsen provides security-enforced recovery services for small businesses through Bald Eagle Network Services.',
            ],
            'about_sections' => [
                [
                    'title' => 'About Bald Eagle Network Services',
                    'paragraphs' => [
                        'Bald Eagle Network Services exists for small businesses that need dependable system recovery with security built in from the start.',
                        'The focus is simple: keep systems reliable, reduce avoidable risk, and make sure the person doing the work is the person accountable for it.',
                        'This is not a support queue model. All work is handled directly.',
                    ],
                ],
                [
                    'title' => 'Operator-Led IT and Security',
                    'paragraphs' => [
                        'Steve Carlsen personally handles the work. No outsourcing. No ticket-routing layers.',
                        'You work with the person responsible for your systems. If something breaks, the same person who built or configured it is responsible for fixing it.',
                        'That keeps communication shorter, troubleshooting faster, and accountability clear.',
                    ],
                ],
                [
                    'title' => 'Background and Experience',
                    'paragraphs' => [
                        'Steve has 26 years of technical operations experience across in-house environments and operator-led service delivery.',
                        'That background includes server operations, workstation and printer reliability, Microsoft 365 administration, endpoint security, backup processes, network and firewall work, and direct user continuity support.',
                        'The goal is not to oversell specialized expertise. It is to bring long practical experience to the kinds of problems small businesses actually deal with every week.',
                    ],
                ],
                [
                    'title' => 'Security-First Approach',
                    'paragraphs' => [
                        'Security comes first, reliability second, because weak systems eventually become unreliable systems.',
                        'The work centers on sensible controls, Microsoft 365 security, Microsoft Defender, firewall and network hygiene, OS firewall settings, backup implementation, and restore verification processes.',
                        'The emphasis is practical risk reduction, not dramatic cybersecurity claims.',
                    ],
                ],
                [
                    'title' => 'Who This Is For',
                    'paragraphs' => [
                        'Bald Eagle is built for small businesses with roughly 5 to 20 employees that cannot justify a full internal IT department.',
                        'That often includes dental offices, law offices, contractors, and service businesses that need their systems to work without constant hand-holding.',
                        'Location coverage is centered on the Salt Lake region and Utah, with remote support handled where it makes sense and without overpromising coverage.',
                    ],
                ],
                [
                    'title' => 'How Work Is Handled',
                    'paragraphs' => [
                        'Work is scoped directly, handled directly, and communicated directly.',
                        'There is no sales handoff, no dispatcher, and no separate implementation layer. Problems are reviewed with the client\'s team, priorities are set clearly, and the work moves forward without extra routing.',
                        'That approach fits businesses that want straightforward help instead of a support queue experience.',
                    ],
                ],
                [
                    'title' => 'Certifications and Tools',
                    'paragraphs' => [
                        'Current certifications include Microsoft Certified Professional (MCP) and CompTIA A+.',
                        'Net+ and Security+ are planned. Cisco certification is being considered.',
                        'Common tools and platforms include Microsoft 365, Microsoft Defender, pfSense, OS firewalls, and backup implementation and restore verification processes.',
                    ],
                ],
                [
                    'title' => 'Accountability',
                    'paragraphs' => [
                        'Small businesses do better when responsibility is obvious.',
                        'Bald Eagle is built around direct ownership of the work. You know who to call, who made the decision, and who is responsible for the result.',
                        'If something breaks, the same person who built or configured it is responsible for fixing it.',
                    ],
                ],
            ],
            'fit_cards' => [
                [
                    'title' => 'Direct Handling',
                    'copy' => 'All work is handled directly by Steve Carlsen, with no outsourced queue and no handoff between layers.',
                ],
                [
                    'title' => 'Security First',
                    'copy' => 'Security-enforced recovery for small businesses, with reliability following from systems that are configured and maintained correctly.',
                ],
                [
                    'title' => 'Best Fit',
                    'copy' => 'Small businesses with 5-20 employees that need accountable support but do not need a full internal IT department.',
                ],
            ],
            'secondary_cta' => [
                'href' => page_href('services'),
                'label' => 'See Recovery-First Services',
            ],
            'final_cta' => [
                'title' => 'Start a Recovery Assessment with the person responsible for the work.',
                'copy' => 'No ticket queues. No escalation layers. The same operator reviews the environment, defines the next step, and owns the result.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
            'related_links' => ['security-risk-assessments', 'monthly-it-support-plans', 'backup-disaster-recovery'],
        ],
        'backup-disaster-recovery' => [
            'slug' => 'backup-disaster-recovery',
            'path' => '/backup-disaster-recovery',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Backup & Recovery Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Backup and recovery services in Salt Lake City for businesses that need verified restores and practical continuity planning.',
            'hero_kicker' => 'Backup & Disaster Recovery',
            'hero_title' => 'Backup, Recovery, and Restore Confidence',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses monitor backups, verify restores, and shorten recovery time when ransomware, deletion, or system failure hits.',
            'card_title' => 'Backup & Disaster Recovery',
            'card_copy' => 'Backup monitoring, restore testing, retention review, and recovery planning tied to business continuity.',
            'pain_points' => [
                'Backups appear healthy but no one knows whether key data can actually be restored',
                'Retention settings do not reflect operational downtime or legal needs',
                'Critical systems have no documented order of recovery after an incident',
                'Ransomware planning stops at backup status instead of restore readiness',
            ],
            'included' => [
                'Backup configuration and monitoring review',
                'Recovery priorities aligned to business operations',
                'Restore testing guidance or supervised execution',
                'Continuity recommendations tied to actual systems and dependencies',
            ],
            'who_for_title' => 'For offices that cannot absorb data loss or long downtime.',
            'who_for_copy' => 'This service fits small professional-service businesses and local offices that rely on file access, account access, line-of-business systems, or shared data to stay open.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'When recovery planning is vague, incident response becomes guesswork. That extends downtime and turns manageable failures into business-wide disruption.',
                'Verified restores create a more honest continuity plan because owners can see what recovery would actually require before a real incident forces the answer.',
            ],
            'deliverables' => [
                'Backup and recovery posture review',
                'Prioritized restore and continuity concerns',
                'Retention, monitoring, and restoration recommendations',
                'Defined next steps for remediation or ongoing continuity oversight',
            ],
            'cta_title' => 'If you have never restored it, you do not know if it comes back.',
            'cta_copy' => 'Most backups exist but are never tested. Start with the system that would stop the business first.',
            'contact_service_type' => 'backup-dr',
            'primary_cta_label' => 'Prove Your Backup Works',
            'process_heading' => 'How backup verification turns into a real recovery plan.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Review', 'copy' => 'Identify the backups, systems, and restore assumptions tied to your highest downtime risk.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Confirm what can be restored, what is untested, and where ransomware pressure would break the plan.'],
                ['step' => '03', 'title' => 'Prioritize', 'copy' => 'Deliver the next actions for restore testing, retention fixes, and continuity improvements.'],
            ],
            'secondary_cta' => ['href' => page_href('monthly-it-support-plans'), 'label' => 'Review Ongoing Backup Verification'],
            'related_links' => ['monthly-it-support-plans', 'security-risk-assessments', 'case-study-backup-recovery-failure', 'case-study-security-recovery-failure'],
        ],
        'compliance-readiness' => [
            'slug' => 'compliance-readiness',
            'path' => '/compliance-readiness',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Compliance Readiness Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Continuity and control readiness services in Salt Lake City for small businesses preparing for audits, insurance reviews, or client pressure.',
            'hero_kicker' => 'Compliance Readiness',
            'hero_title' => 'Compliance Readiness Support',
            'hero_intro' => 'Bald Eagle helps Salt Lake City businesses prepare for audits and client reviews by tightening controls, documentation, access standards, and device discipline.',
            'card_title' => 'Compliance Readiness',
            'card_copy' => 'Control cleanup and remediation support ahead of audits, questionnaires, and client reviews.',
            'pain_points' => [
                'Client or insurance questionnaires exposing weak answers',
                'No documented control owner for key security areas',
                'Account access and endpoint settings that are inconsistent',
                'Too much scrambling right before a review or renewal',
            ],
            'included' => [
                'Gap review against stated readiness needs',
                'Control cleanup recommendations and remediation support',
                'Documentation assistance for current-state explanations',
                'Alignment between support work, security work, and audit pressure',
            ],
            'who_for_title' => 'For businesses preparing for outside scrutiny.',
            'who_for_copy' => 'This service fits organizations that are facing a client security review, insurance requirement, compliance checklist, or internal pressure to clean up control issues before they become expensive.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Compliance pressure often reveals operational weaknesses that already exist. Waiting until the deadline usually makes remediation more expensive and more disruptive.',
                'Readiness work gives owners a more controlled way to fix the basics, document the environment, and stop guessing about what is actually missing.',
            ],
            'deliverables' => [
                'Readiness gap summary',
                'Control remediation priorities',
                'Implementation support recommendations',
                'Defined path into project work or monthly support if needed',
            ],
            'cta_title' => 'If controls break under pressure, recovery breaks with them.',
            'cta_copy' => 'Start with the weakest control, the audit pressure, or the requirement your business cannot defend today.',
            'contact_service_type' => 'compliance',
            'primary_cta_label' => 'Identify Gaps in Your Backup and Recovery Process',
            'process_heading' => 'How readiness work moves from outside pressure to practical fixes.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Identify', 'copy' => 'Review the questionnaire, insurance demand, or audit pressure revealing the current gap.'],
                ['step' => '02', 'title' => 'Map', 'copy' => 'Tie the control weakness to recovery, access, or continuity risk inside the real environment.'],
                ['step' => '03', 'title' => 'Close', 'copy' => 'Return a prioritized remediation path with the documentation or cleanup steps that matter first.'],
            ],
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Test What Actually Fails During an Outage'],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'network-security'],
        ],
        'contact' => [
            'slug' => 'contact',
            'path' => '/contact',
            'nav_key' => 'contact',
            'template' => 'contact',
            'title' => 'Request a Cybersecurity Risk Assessment | Salt Lake Metro | Bald Eagle',
            'description' => 'Request a cybersecurity risk assessment for your Salt Lake metro business and find backup, recovery, and ransomware weaknesses before downtime does.',
            'hero_kicker' => 'Risk Assessment Request',
            'hero_title' => 'Request a Recovery Assessment',
            'hero_intro' => 'Use this short form to start a Recovery Assessment. It checks whether your backups, restore process, and failure response are actually usable.',
            'contact_points' => [
                'Name the system, data set, or workflow your team cannot lose',
                'Tell us when you last completed a successful restore test',
                'Flag whether ransomware, downtime, or account access is the bigger concern',
                'Share any looming deadline such as insurance, audit, or client pressure',
                'Keep it short if needed; the goal is to identify the next review step quickly',
            ],
            'response_points' => [
                'Direct response with defined scope and next action',
                'Requests filtered to Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Recommendation for assessment findings, backup verification, recovery planning, or continuity monitoring',
                'No ticket maze and no outsourced sales handoff',
            ],
            'form_title' => 'Start a Recovery Assessment',
            'form_copy' => 'If you have never restored your data, you do not know whether you have a backup. A Recovery Assessment shows what works and what fails.',
        ],
        'faq' => [
            'slug' => 'faq',
            'path' => '/faq',
            'nav_key' => '',
            'template' => 'faq',
            'title' => 'Recovery Assessment FAQ | Bald Eagle Network Services',
            'description' => 'Answers about Recovery Assessments, backup recovery risk, restore testing, and Salt Lake metro service fit.',
            'hero_kicker' => 'Frequently Asked Questions',
            'hero_title' => 'Recovery Assessment FAQ',
            'hero_intro' => 'These answers cover fit, assessment scope, backup validation, restore testing, and local coverage in the Salt Lake metro.',
            'faq_items' => [
                ['question' => 'What size company is the best fit?', 'answer' => 'The public site is written for small professional-service businesses and local offices with roughly 5 to 20 employees that depend on continuity but do not have deep internal IT coverage.'],
                ['question' => 'Do you only support businesses in Salt Lake?', 'answer' => 'Yes. Service is limited to the Salt Lake metro and nearby businesses within about a 30-mile radius.'],
                ['question' => 'Can we start with an assessment instead of ongoing service?', 'answer' => 'Yes. Most engagements begin with a Recovery Assessment to establish facts before discussing remediation or monitoring.'],
                ['question' => 'Do you provide broad day-to-day coverage for every system issue?', 'answer' => 'The public site is intentionally focused on backup and recovery outcomes, recovery testing, continuity planning, and scoped security work that protects those outcomes.'],
                ['question' => 'What does continuity monitoring cover?', 'answer' => 'Continuity monitoring is limited oversight tied to backup health, recovery readiness, retention concerns, and follow-through on issues that would materially affect downtime or restore success.'],
                ['question' => 'Do you handle account access and endpoint issues?', 'answer' => 'Yes, but only where those systems affect recovery speed, identity protection, file access, or business continuity. The goal is not broad platform administration for its own sake.'],
                ['question' => 'Can you help with security hardening?', 'answer' => 'Yes, in a scoped way. Hardening work is aimed at reducing blast radius, tightening access, and protecting recovery paths rather than turning the engagement into a broad network security program.'],
                ['question' => 'What happens after we submit the form?', 'answer' => 'The request is reviewed for fit, urgency, and service area. You get a direct response with the best next step and scope for the assessment.'],
            ],
            'final_cta' => [
                'title' => 'Stop guessing what happens when systems fail.',
                'copy' => 'Talk directly to the operator and find out what recovery actually looks like in your environment.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
        ],
        'home' => [
            'slug' => 'home',
            'path' => '/',
            'nav_key' => 'services',
            'template' => 'home',
            'title' => 'Small Business Cybersecurity Risk Assessments in Salt Lake City | Bald Eagle',
            'description' => 'Request a small-business cybersecurity risk assessment in the Salt Lake metro. Verify backup readiness and recovery planning before downtime hits.',
            'hero_kicker' => 'Salt Lake Recovery Readiness',
            'hero_title' => 'If your systems went down today, how long would it take to recover?',
            'hero_intro' => 'Backups are not recovery. Bald Eagle uses a Recovery Assessment to show Salt Lake metro businesses what restore reality looks like before ransomware or failure forces the answer.',
            'hero_panel_label' => 'Questions To Answer Now',
            'trust_points' => [
                'When was your last successful restore test?',
                'Could your business recover from ransomware today?',
                'What happens if your main system is unavailable tomorrow?',
                'Are your backups verified or only reporting green?',
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Prove Your Backup Works'],
            'trust_strip' => [
                'Risk assessment first',
                'Verified recovery testing',
                'Salt Lake metro only',
                'Backup restore validation',
                'Reduced downtime',
            ],
            'core_services' => [
                [
                    'title' => 'Dental Offices',
                    'copy' => 'Chart systems, imaging access, and scheduling continuity checked against restore order and tested recovery reality.',
                    'href' => page_href('backup-disaster-recovery'),
                    'link_label' => 'Prove Your Backup Works',
                ],
                [
                    'title' => 'Legal Offices',
                    'copy' => 'Matter files, account access controls, and ransomware recovery dependencies checked before a disruption.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Find Out If Your Systems Can Be Recovered',
                ],
                [
                    'title' => 'Construction Firms',
                    'copy' => 'Field-to-office file flow, remote access controls, and backup restore testing aligned to active project risk.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Identify What Fails in Your Current Setup',
                ],
                [
                    'title' => 'Professional Service Offices',
                    'copy' => 'Owner-led teams get clear findings, scoped remediation, and continuity monitoring where it is justified.',
                    'href' => page_href('network-security'),
                    'link_label' => 'Assess Your Exposure to Ransomware Spread',
                ],
            ],
            'founder_section' => [
                'eyebrow' => 'Operator-Led Trust',
                'title' => 'Who You’re Trusting With Your Systems',
                'paragraphs' => [
                    'Bald Eagle Network Services is operated directly by Steve Carlsen, a technical operator with 26 years of hands-on experience across in-house environments and direct client operations.',
                    'All work is handled directly. No outsourcing. No ticket-routing layers. You work with the person responsible for securing, supporting, and fixing your systems.',
                    'The focus is security-enforced recovery for small businesses that need reliable systems but cannot justify a full internal technology team.',
                ],
                'card_title' => 'What This Means',
                'card_points' => [
                    'Direct accountability from the founder/operator',
                    'Security-first decisions for small business environments',
                    'Built for dental offices, law offices, contractors, and service businesses',
                ],
                'cta_href' => page_href('about'),
                'cta_label' => 'Talk Directly to the Operator',
            ],
            'warning_signs' => [
                [
                    'title' => 'When was your last successful restore test?',
                    'copy' => 'Teams discover restore failures only during a real incident because test restores were never run against critical workloads.',
                ],
                [
                    'title' => 'Could your business recover from ransomware today?',
                    'copy' => 'Former staff access, broad permission groups, and weak MFA create avoidable exposure and slow recovery after account compromise.',
                ],
                [
                    'title' => 'What gets restored first if the main system fails?',
                    'copy' => 'Owners know systems are important but cannot name what gets restored first or what dependencies block operations.',
                ],
                [
                    'title' => 'Are you relying on backups without a continuity plan?',
                    'copy' => 'Without recovery sequencing and control hardening, backups alone do not prevent extended downtime.',
                ],
            ],
            'why_cards' => [
                [
                    'title' => 'Assessment first',
                    'copy' => 'Every engagement starts with a defined Recovery Assessment to establish real risk, not assumptions.',
                ],
                [
                    'title' => 'Scope stays controlled',
                    'copy' => 'Recommendations are prioritized by operational impact and recovery risk, not by broad technology wish lists.',
                ],
                [
                    'title' => 'Accountability stays local',
                    'copy' => 'Coverage remains inside the Salt Lake metro so on-site recovery, remediation, and follow-through remain practical.',
                ],
            ],
            'proof_strip' => [
                [
                    'title' => 'Recover faster from incidents',
                    'copy' => 'Know what must be restored first, what recovery dependencies exist, and where the real downtime risk lives.',
                ],
                [
                    'title' => 'Prove backups before failure',
                    'copy' => 'A green dashboard does not mean your business can recover. Restore testing does.',
                ],
                [
                    'title' => 'Contain ransomware downtime',
                    'copy' => 'Tighten account access and recovery dependencies so an attack does not turn into a prolonged shutdown.',
                ],
            ],
            'case_study_block' => [
                'eyebrow' => 'Proof Of Work',
                'title' => 'Real Recovery Failure Example',
                'paragraphs' => [
                    'A small office had backups in place, but recovery had never been tested. When the restore process was checked, critical gaps appeared before a real outage exposed them.',
                    'A second scenario shows how weak access control can let destructive actions reach backup systems, turning a recoverable event into total recovery failure.',
                ],
                'card_title' => 'Backup Existed. Recovery Failed.',
                'card_copy' => 'A small office had backups in place, but recovery had never been tested. When the restore process was checked, critical gaps appeared before a real outage exposed them.',
                'points' => [
                    'Backup coverage was incomplete',
                    'Critical data locations were missing',
                    'Permissions did not restore cleanly',
                    'Recurring verification had to be added',
                ],
                'href' => page_href('case-study-backup-recovery-failure'),
                'label' => 'Read the Case Study',
                'secondary_href' => page_href('case-study-security-recovery-failure'),
                'secondary_label' => 'Read the Security Exposure Example',
            ],
            'engagements' => [
                [
                    'title' => 'If You Are Stable',
                    'copy' => 'Monthly backup and recovery verification keeps backup validation and recovery risk from drifting back into assumptions.',
                    'points' => [
                        'Backup and restore monitoring follow-through',
                        'Recovery issue tracking and prioritization',
                        'Escalation when continuity risk increases',
                    ],
                    'href' => page_href('monthly-it-support-plans'),
                    'link_label' => 'Review How Your Recovery Is Maintained Over Time',
                ],
                [
                    'title' => 'If Gaps Are Found',
                    'copy' => 'Go back through the Recovery Assessment to define what fails first, what must be corrected, and what should be re-tested before it matters.',
                    'points' => [
                        'Defined recovery priorities',
                        'Direct operator review',
                        'Clear next action before another failure',
                    ],
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Start a Recovery Assessment',
                ],
            ],
            'access_control' => [
                'title' => 'Account access controls are part of recovery, not a side task.',
                'copy' => 'Identity, email and file access, and admin boundaries directly affect recovery speed after ransomware, account compromise, or data loss.',
                'points' => [
                    'Identity, MFA, and access policy review',
                    'Email and file access dependency checks',
                    'Administrative boundary cleanup tied to restore readiness',
                    'Scoped hardening around business-critical workflows',
                ],
            ],
            'service_area' => [
                'title' => 'Local coverage limited to the Salt Lake metro.',
                'copy' => 'Bald Eagle works within a 30-mile radius of Salt Lake City so continuity planning, on-site recovery work, and follow-through stay realistic.',
                'points' => [
                    'Salt Lake City and nearby commercial corridors',
                    'Reasonable travel windows for on-site recovery work',
                    'No oversized multi-market footprint',
                    'Local businesses only',
                ],
            ],
            'process' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Review business impact, recovery dependencies, and the controls most likely to fail under pressure.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Test what can be restored, what fails silently, and what assumptions are currently unsafe.'],
                ['step' => '03', 'title' => 'Harden', 'copy' => 'Tighten the access and control gaps that would make a recovery event worse.'],
                ['step' => '04', 'title' => 'Recover', 'copy' => 'Document next steps so the business can respond faster when an incident actually happens.'],
            ],
            'faq_items' => [
                [
                    'question' => 'Do you only work with companies in Salt Lake?',
                    'answer' => 'Yes. The public site is intentionally limited to the Salt Lake metro and nearby businesses within roughly 30 miles.',
                ],
                [
                    'question' => 'Can we start with a single project?',
                    'answer' => 'Yes, but the first step is still an assessment so project scope is tied to risk and recoverability.',
                ],
                [
                    'question' => 'Do you support account access and identity cleanup?',
                    'answer' => 'Yes, where account access affects recovery speed, identity risk, file access, or business continuity. The focus is continuity, not broad platform administration for its own sake.',
                ],
                [
                    'question' => 'What kinds of businesses are the best fit?',
                    'answer' => 'Small professional-service businesses and local offices with roughly 5 to 20 employees that rely on continuity and need clearer recovery outcomes.',
                ],
            ],
            'final_cta' => [
                'title' => 'Find out if your systems can be recovered.',
                'copy' => 'If you have never restored it, you have not proven it.',
            ],
        ],
        'monthly-it-support-plans' => [
            'slug' => 'monthly-it-support-plans',
            'path' => '/monthly-it-support-plans',
            'nav_key' => 'plans',
            'template' => 'commercial',
            'title' => 'Monthly Backup and Recovery Verification Plans | Bald Eagle Network Services',
            'description' => 'Monthly backup monitoring, restore verification, and recovery readiness oversight for small businesses that need proof their systems can be recovered.',
            'hero_kicker' => 'Ongoing Recovery Verification',
            'hero_title' => 'Monthly Backup and Recovery Verification Plans',
            'hero_intro' => 'These plans provide ongoing backup monitoring, restore verification, recovery readiness review, and failure-response preparation for small businesses that cannot afford to discover problems during an outage.',
            'card_title' => 'Monthly Backup and Recovery Verification',
            'card_copy' => 'Monthly backup monitoring, restore verification, and recovery follow-through tied to real failure conditions.',
            'pain_points' => [
                'Backup jobs report success but nobody is checking whether protected systems can actually be restored',
                'Restore testing gets delayed until an outage, audit, or ransomware event forces the issue',
                'Recovery gaps stay open because nobody is reviewing them month to month',
                'Owners need steady visibility into backup health without turning the work into a general IT contract',
            ],
            'included' => [
                'Backup job monitoring and exception review',
                'Restore verification scheduling and follow-through',
                'Monthly review of recovery blockers, retention concerns, and readiness drift',
                'Failure-response preparation tied to the systems that matter first',
            ],
            'who_for_title' => 'For companies that need recovery verified, not assumed.',
            'who_for_copy' => 'These plans fit businesses that already know backup and recovery cannot be left to a dashboard, a vendor promise, or an annual panic review.',
            'why_title' => 'Why restore testing matters',
            'why_paragraphs' => [
                'Backup status alone does not prove recoverability. Restore testing is what shows whether the data is usable, whether the process works, and whether the business could actually get back online under pressure.',
                'Monthly verification keeps backup and recovery from drifting back into assumptions after the initial assessment is done.',
            ],
            'deliverables' => [
                'Monthly summary of backup status, verification results, and unresolved recovery risks',
                'Restore testing follow-through on the systems that matter first',
                'Clear notice when backup or recovery gaps are found',
                'Defined next actions for remediation, hardening, or another Recovery Assessment review',
            ],
            'cta_title' => 'When backup verification stops, recovery drifts back into guesswork.',
            'cta_copy' => 'Start with a Recovery Assessment. The monthly plan only works when the business knows what must be protected, what has to be restored first, and what still fails under pressure.',
            'contact_service_type' => 'monthly-backup-verification',
            'primary_cta_label' => 'Request a Recovery Assessment',
            'process_heading' => 'How monthly backup and recovery verification works.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Monitor', 'copy' => 'Review backup health, failures, missed jobs, and retention concerns tied to business-critical systems.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Check whether restore testing is current, whether the last result proved anything useful, and where recovery confidence is still weak.'],
                ['step' => '03', 'title' => 'Respond', 'copy' => 'When backup or recovery gaps are found, define the fix path quickly instead of letting the issue sit until the next outage.'],
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Prove Your Backup Works'],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'network-security'],
        ],
        'network-security' => [
            'slug' => 'network-security',
            'path' => '/network-security',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Scoped Security Hardening in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Scoped security hardening in Salt Lake City for businesses that need better access control, reduced blast radius, and stronger recovery outcomes.',
            'hero_kicker' => 'Security Hardening',
            'hero_title' => 'Scoped Security Hardening',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses tighten the controls that most affect ransomware resilience, recovery speed, and continuity risk.',
            'card_title' => 'Scoped Security Hardening',
            'card_copy' => 'Targeted hardening for identity, remote access, segmentation, and recovery-critical systems.',
            'pain_points' => [
                'Remote access or identity controls would make a recovery event harder to contain',
                'Flat networks and broad permissions create too much blast radius',
                'Security changes were made reactively and never cleaned up',
                'Critical systems lack the access boundaries needed for credible continuity planning',
            ],
            'included' => [
                'Identity, remote access, and edge control review',
                'Segmentation or trust-boundary recommendations where needed',
                'Scoped corrective hardening aligned to continuity priorities',
                'Recommendations that support backup and recovery outcomes',
            ],
            'who_for_title' => 'For businesses that know their controls are too loose to trust during an incident.',
            'who_for_copy' => 'This service is for companies that need practical hardening to support recovery outcomes, not a broad network security program or enterprise theater.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Small business recovery gets harder when identity, remote access, and internal trust boundaries are loose. Weak controls increase both the chance of compromise and the scope of disruption.',
                'Hardening here is about removing easy mistakes, tightening trust boundaries, and protecting the systems that would matter most during recovery.',
            ],
            'deliverables' => [
                'Current-state hardening review',
                'Prioritized corrective actions',
                'Access, segmentation, or control recommendations',
                'Clear next-step plan for remediation work',
            ],
            'cta_title' => 'If ransomware gets in, how far does it spread before you stop it?',
            'cta_copy' => 'Bring the entry point, trust boundary, or control gap that would fail under pressure.',
            'contact_service_type' => 'network-security',
            'primary_cta_label' => 'Assess Your Exposure to Ransomware Spread',
            'process_heading' => 'How targeted hardening work stays tied to resilience instead of bloat.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Identify the identity, remote access, or trust-boundary weakness raising ransomware exposure.'],
                ['step' => '02', 'title' => 'Contain', 'copy' => 'Define the control changes that reduce blast radius without expanding scope into a generic overhaul.'],
                ['step' => '03', 'title' => 'Validate', 'copy' => 'Confirm the hardening actions support backup recovery, continuity, and incident containment goals.'],
            ],
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Test What Actually Fails During an Outage'],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'monthly-it-support-plans'],
        ],
        'privacy-policy' => [
            'slug' => 'privacy-policy',
            'path' => '/privacy-policy',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Privacy Policy | Bald Eagle Network Services',
            'description' => 'Privacy policy for the Bald Eagle Network Services public website and contact request form.',
            'hero_kicker' => 'Privacy Policy',
            'hero_title' => 'How contact requests and site data are handled.',
            'hero_intro' => 'This privacy policy applies to the public website for Bald Eagle Network Services and explains the limited data collected through contact requests.',
            'sections' => [
                [
                    'title' => 'Information Collected',
                    'paragraphs' => [
                        'The public website collects the information you submit through the contact form, including name, company, email address, phone number, preferred contact method, employee count, main concern, assessment type, and message content.',
                        'Basic technical request information such as IP address and browser user agent may also be logged for security, abuse prevention, and troubleshooting.',
                    ],
                ],
                [
                    'title' => 'How Information Is Used',
                    'paragraphs' => [
                        'Submitted information is used to review service fit, respond to inquiries, and manage follow-up related to recovery testing, continuity monitoring, remediation projects, or related support requests.',
                        'Information is not sold or rented through the public website.',
                    ],
                ],
                [
                    'title' => 'Security and Retention',
                    'paragraphs' => [
                        'Reasonable administrative and technical safeguards are used on the public website, including CSRF protection, validation, and anti-abuse controls on the contact form.',
                        'Inquiry data is retained only as long as needed for business communication, recordkeeping, and security review.',
                    ],
                ],
                [
                    'title' => 'Contact',
                    'paragraphs' => [
                        'Questions about this privacy policy can be submitted through the public contact form.',
                    ],
                ],
            ],
        ],
        'security-risk-assessments' => [
            'slug' => 'security-risk-assessments',
            'path' => '/recovery-assessment',
            'nav_key' => 'services',
            'template' => 'recovery-assessment',
            'title' => 'Recovery Assessment | Backup & Recovery Review | Bald Eagle Network Services Utah',
            'description' => 'Structured backup and recovery review for Utah small businesses. Verify what is backed up, what restores, and what fails before an outage.',
            'hero_kicker' => 'Primary Conversion Path',
            'hero_title' => 'Recovery Assessment',
            'hero_intro' => 'If everything fails, your systems can be recovered, but only if recovery has been tested and proven.',
            'hero_paragraphs' => [
                'This is a structured review of backup and recovery capability for small businesses that cannot afford to guess during an outage.',
                'The focus is real-world failure, not configuration assumptions, vendor dashboards, or backup jobs that only look healthy on paper.',
            ],
            'card_title' => 'Recovery Assessment',
            'card_copy' => 'Structured backup and recovery review focused on what actually fails, what restores, and what has to be fixed first.',
            'assessment_standard' => [
                'Backup success is not treated as proof of recovery.',
                'Documented restore steps matter because pressure exposes missing process fast.',
                'Security weaknesses that slow or block recovery are part of the review.',
            ],
            'what_this_is' => [
                'A Recovery Assessment is a direct review of whether your backup and recovery process can hold up when systems actually fail.',
                'It checks what is being protected, what is missing, what restore process exists, and whether the business could keep operating under real pressure.',
                'If recovery has not been tested, it is not considered reliable.',
            ],
            'what_is_checked_cards' => [
                [
                    'title' => 'Backup Scope',
                    'copy' => 'Check what systems are currently backed up and whether business-critical servers, files, cloud data, and line-of-business systems are actually included.',
                ],
                [
                    'title' => 'Data Coverage',
                    'copy' => 'Review what data is protected, what is excluded, and whether the gaps are known or only discovered after a failure.',
                ],
                [
                    'title' => 'Backup Completion',
                    'copy' => 'Confirm whether backup jobs are completing successfully and whether failures are being seen, ignored, or hidden by bad assumptions.',
                ],
                [
                    'title' => 'Restore Process',
                    'copy' => 'Check whether a restore process exists, whether it is documented, and whether anyone could follow it under pressure.',
                ],
                [
                    'title' => 'Restore Testing',
                    'copy' => 'Review whether a restore has ever been tested, what was tested, and whether the result proved anything useful.',
                ],
                [
                    'title' => 'Recovery Time',
                    'copy' => 'Estimate how long recovery would actually take based on dependencies, order of operations, and what has to come back first.',
                ],
                [
                    'title' => 'Destructive Events',
                    'copy' => 'Measure exposure to ransomware, deletion, corruption, and other destructive events that turn backup assumptions into business downtime.',
                ],
                [
                    'title' => 'Access Risk',
                    'copy' => 'Review administrative access, shared credentials, identity risk, and control failures that directly affect recovery speed or containment.',
                ],
            ],
            'what_you_get' => [
                'Clear breakdown of current backup coverage',
                'Identified gaps in recovery capability',
                'Realistic recovery expectations instead of assumptions',
                'Prioritized list of what needs to be fixed first',
                'Plain-language explanation of the risks',
            ],
            'what_you_get_copy' => [
                'The output is meant to be usable. It shows what is covered, what is missing, what probably fails under pressure, and what deserves immediate attention.',
                'It is written so an owner can understand the operational risk without needing a vendor translation layer.',
            ],
            'what_happens_after' => [
                'Findings are reviewed directly with Steve Carlsen, not handed off to a different person after the assessment is finished.',
                'Critical gaps are addressed first, recovery process is corrected where needed, and restore testing is performed when the business is relying on assumptions.',
                'If the environment needs follow-through, ongoing validation can be set up without turning the work into a support-queue relationship.',
            ],
            'after_steps' => [
                'Findings reviewed directly with Steve Carlsen',
                'Critical recovery gaps addressed first',
                'Recovery process implemented or corrected',
                'Restore testing performed where needed',
                'Ongoing validation set up if justified',
                'No handoff and no escalation layers',
            ],
            'what_this_is_not_copy' => [
                'This is not a paper review. Systems are evaluated based on what actually happens when something fails.',
                'The point is to identify whether recovery works, not to produce a checklist that avoids hard questions.',
            ],
            'what_this_is_not' => [
                'Not a generic IT audit',
                'Not a checklist exercise',
                'Not a sales presentation',
                'Not based on assumptions or vendor claims',
            ],
            'why_this_matters_cards' => [
                [
                    'title' => 'Most Backups Are Never Tested',
                    'copy' => 'Many businesses only find out a restore fails when an outage is already happening and time is already lost.',
                ],
                [
                    'title' => 'Pressure Exposes Weak Recovery',
                    'copy' => 'Recovery failures show up when people are rushed, access is broken, documentation is missing, and the restore order was never thought through.',
                ],
                [
                    'title' => 'Downtime Does The Damage',
                    'copy' => 'The real cost shows up when systems stay down, staff stop working, and critical data is unavailable longer than expected.',
                ],
                [
                    'title' => 'Security And Recovery Are Connected',
                    'copy' => 'Weak admin controls, ransomware spread, and poor access discipline directly affect whether recovery is possible and how long it takes.',
                ],
            ],
            'why_this_matters_copy' => [
                'When systems fail, recovery is what determines whether the business continues operating.',
            ],
            'proof_block' => [
                'eyebrow' => 'Proof Of Work',
                'title' => 'Real Example: Backup Existed. Recovery Failed.',
                'paragraphs' => [
                    'One small office had backups in place, no obvious alerts, and every reason to assume recovery would work.',
                    'The recovery test showed missing data, broken permissions, no documented restore process, and recovery time expectations that were not grounded in reality.',
                    'A second case study demonstrates how weak access control can expose backup systems to destructive actions and break recovery entirely.',
                ],
                'card_eyebrow' => 'Case Study #1',
                'card_title' => 'Backup Existed. Recovery Failed.',
                'card_copy' => 'See what was found, what failed during restore testing, and what had to be corrected before the business could rely on recovery.',
                'href' => page_href('case-study-backup-recovery-failure'),
                'label' => 'Read the Recovery Failure Example',
                'secondary_href' => page_href('case-study-security-recovery-failure'),
                'secondary_label' => 'Read the Security Exposure Example',
            ],
            'submission_clarity' => [
                'title' => 'What Happens After You Submit',
                'points' => [
                    'You will receive a direct response within one business day.',
                    'You will hear directly from Steve Carlsen.',
                    'Your situation is reviewed first, clarification questions are asked if needed, and the next step is then scheduled.',
                    'This is not a sales call, not a generic consultation, and not outsourced.',
                ],
                'what_you_get_title' => 'What You Will Get',
                'what_you_get' => [
                    'Clear understanding of recovery capability',
                    'Identification of failure points',
                    'Prioritized next steps',
                ],
                'trust_line' => 'You are not handed off. The same person reviewing your systems is responsible for fixing them.',
            ],
            'contact_service_type' => 'risk-assessment',
            'primary_cta_label' => 'Start a Recovery Assessment',
            'secondary_cta' => ['href' => page_href('about'), 'label' => 'Talk Directly to the Operator'],
            'cta_supporting_line' => 'Find out what actually happens when your systems fail.',
            'related_links' => ['backup-disaster-recovery', 'monthly-it-support-plans', 'network-security'],
        ],
        'case-study-backup-recovery-failure' => [
            'slug' => 'case-study-backup-recovery-failure',
            'path' => '/case-study-backup-recovery-failure',
            'nav_key' => 'case-study-backup-recovery-failure',
            'template' => 'case-study',
            'title' => 'Case Study: Backup Existed, Recovery Failed | Bald Eagle Network Services',
            'description' => 'Restore testing exposed missing data, broken permissions, and unrealistic recovery expectations in a small-office backup setup.',
            'hero_kicker' => 'Case Study #1',
            'hero_title' => 'Backup Existed. Recovery Failed.',
            'hero_intro' => 'Backups are not reliable unless they have been proven to restore.',
            'card_title' => 'Backup Existed. Recovery Failed.',
            'card_copy' => 'A recovery test exposed missing data, broken restore steps, and backup assumptions that would have failed under pressure.',
            'situation' => [
                'A small office with fewer than 15 employees believed the environment was protected. Backups were running, no obvious alerts were being reported, and there was an assumption that data could be recovered if needed.',
                'No one had ever performed a full restore. The backup system looked functional, but the business had never tested what would actually happen under failure.',
            ],
            'what_was_wrong' => [
                'Backup coverage was incomplete',
                'Key data locations were not included',
                'No documented restore process existed',
                'No one had performed a recovery',
                'Recovery time expectations were unrealistic',
            ],
            'what_failed' => [
                'Critical data could not be restored from the most recent backup',
                'Older backup points existed but were incomplete',
                'File structure and permissions were not preserved correctly',
                'Recovery would have taken longer than expected',
            ],
            'what_was_fixed' => [
                'Reviewed and corrected backup scope',
                'Verified backup completion and consistency',
                'Defined and documented restore steps',
                'Performed restore testing',
                'Established realistic recovery expectations',
                'Added recurring verification',
            ],
            'why_it_mattered' => [
                'The business was not deciding between good and bad backup software. It was relying on assumptions that would have failed under pressure.',
                'If a real outage or ransomware event had forced recovery first, the business would have discovered the missing data and restore problems when downtime was already costing time and money.',
                'Backups are not reliable unless they have been proven to restore.',
            ],
            'outcome_title' => 'The business moved from assumption to proof.',
            'outcome' => [
                'The environment went from assuming backups worked to having a verified recovery process with corrected scope, tested restore steps, and realistic recovery expectations.',
                'That changed the conversation from hoping the backup job was enough to knowing what recovery would actually require.',
            ],
            'check_cards' => [
                [
                    'title' => 'Check Backup Scope',
                    'copy' => 'Confirm the systems and data that matter most are actually included. Green backup status does not prove complete coverage.',
                ],
                [
                    'title' => 'Check Restore Steps',
                    'copy' => 'If no one can describe the restore process under pressure, recovery is still guesswork.',
                ],
                [
                    'title' => 'Check A Real Restore',
                    'copy' => 'Test whether files, folders, permissions, and application data come back in a usable state.',
                ],
                [
                    'title' => 'Check Recovery Time',
                    'copy' => 'Compare assumed recovery time to what the restore actually takes when dependencies and missing steps get involved.',
                ],
            ],
            'cta' => [
                'title' => 'Check your recovery before it fails.',
                'copy' => 'If no one has tested a restore in your environment, the next outage is when the real answer shows up.',
                'label' => 'Start a Recovery Assessment',
                'href' => recovery_assessment_href('backup-recovery-failure', 'contact-form'),
            ],
            'mid_cta' => [
                'eyebrow' => 'Recovery Action',
                'title' => 'Test Recovery Before It Becomes Downtime',
                'copy' => 'Treat this example as a warning: validate restore behavior before a real outage forces the test.',
                'label' => 'Check Your Recovery Before It Fails',
                'href' => recovery_assessment_href('backup-recovery-failure', 'contact-form'),
            ],
            'secondary_cta' => ['href' => recovery_assessment_href('backup-recovery-failure', 'contact-form'), 'label' => 'Start a Recovery Assessment'],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'monthly-it-support-plans'],
        ],
        'case-study-security-recovery-failure' => [
            'slug' => 'case-study-security-recovery-failure',
            'path' => '/case-study-security-recovery-failure',
            'nav_key' => '',
            'template' => 'case-study',
            'title' => 'Case Study: Security Exposure That Broke Recovery | Bald Eagle Network Services',
            'description' => 'A realistic exposure scenario showing how weak access control can allow destructive actions to compromise backups and break recovery.',
            'hero_kicker' => 'Case Study #2',
            'hero_title' => 'Security Exposure Compromised Recovery',
            'hero_intro' => 'If security fails, recovery can fail with it.',
            'card_title' => 'Security Exposure Compromised Recovery',
            'card_copy' => 'A realistic exposure scenario showing how weak access control can place backup systems on the same destructive path as production systems.',
            'situation' => [
                'A small business with fewer than 20 users relied on remote access and systems that were considered safe enough for day-to-day work.',
                'Backups existed and were reporting normally, but no one had reviewed whether those backup systems could be targeted through the same access paths as production systems.',
            ],
            'what_was_wrong' => [
                'Excessive administrative privileges across user and admin paths',
                'No consistent MFA enforcement on recovery-critical access',
                'Shared credentials and weak access control boundaries',
                'Backup systems reachable from accounts that could be compromised',
                'No separation between production administration and backup administration',
            ],
            'what_failed_eyebrow' => 'Exposure Scenario',
            'what_failed_title' => 'What Could Have Failed',
            'what_failed' => [
                'Ransomware could have reached backup management interfaces',
                'Backup sets could have been deleted or encrypted from compromised accounts',
                'Recovery points could have become unusable before restoration began',
                'The business could have lost practical restore capability during active disruption',
            ],
            'what_was_fixed' => [
                'Reduced privileges to minimum required administrative access',
                'Enforced MFA on all recovery-critical and administrative paths',
                'Separated backup access from general production access',
                'Restricted and monitored administrative paths into backup systems',
                'Validated that backup systems could not be easily destroyed through common compromise paths',
            ],
            'why_it_mattered' => [
                'Backups do not matter if attackers can reach them through the same control paths as production systems.',
                'Recovery depends on both data availability and control integrity. If either fails, the recovery plan fails with it.',
            ],
            'outcome_title' => 'Recovery remained viable under attack conditions.',
            'outcome' => [
                'Backup systems were protected from the same access paths as production systems.',
                'The recovery path remained preserved under realistic attack pressure.',
                'Risk of total recovery failure was significantly reduced.',
            ],
            'check_cards' => [
                [
                    'title' => 'Check Administrative Access',
                    'copy' => 'Verify exactly who has privileged access to recovery-critical systems and whether that scope is truly required.',
                ],
                [
                    'title' => 'Check Backup Deletion Risk',
                    'copy' => 'Confirm compromised accounts cannot delete or encrypt backup data and metadata.',
                ],
                [
                    'title' => 'Check MFA Coverage',
                    'copy' => 'Ensure MFA is enforced anywhere privileged access can alter, destroy, or block recovery.',
                ],
                [
                    'title' => 'Check Backup Isolation',
                    'copy' => 'Validate backup systems are isolated from routine production compromise paths.',
                ],
            ],
            'cta' => [
                'title' => 'Check your recovery before it fails.',
                'copy' => 'If backup controls have not been tested against destructive access scenarios, recovery risk is still unresolved.',
                'label' => 'Check Your Recovery Before It Fails',
                'href' => recovery_assessment_href('security-recovery-risk', 'contact-form'),
            ],
            'secondary_cta' => [
                'href' => recovery_assessment_href('security-recovery-risk', 'contact-form'),
                'label' => 'Start a Recovery Assessment',
            ],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'monthly-it-support-plans'],
        ],
        'service-area' => [
            'slug' => 'service-area',
            'path' => '/service-area',
            'nav_key' => 'service-area',
            'template' => 'service-area',
            'title' => 'Salt Lake Metro Service Area | Bald Eagle Network Services',
            'description' => 'Bald Eagle serves Salt Lake City metro businesses including West Jordan, Sandy, Draper, Murray, and South Jordan for assessment-led recovery and security work.',
            'hero_kicker' => 'Service Area',
            'hero_title' => 'Salt Lake City Service Area',
            'hero_intro' => 'Bald Eagle serves the Salt Lake metro so on-site recovery work, restore testing, and follow-through stay realistic and accountable.',
            'coverage_points' => [
                'Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Typical operating radius of roughly 30 miles',
                'Focused on local offices with 5-20 users',
                'On-site work scheduled around operational windows and business impact',
            ],
            'why_local' => [
                'Travel remains predictable for restore validation and response work',
                'Scope stays grounded in what can actually be delivered on-site',
                'Business owners have direct local accountability, not remote queue handoff',
                'Coverage claims match real operational radius',
            ],
            'local_cards' => [
                ['title' => 'Backup & Recovery', 'copy' => 'For local teams that need verified backups, monitored recovery concerns, and clearer restore expectations.', 'href' => page_href('backup-disaster-recovery')],
                ['title' => 'Monthly Verification', 'copy' => 'For businesses that need ongoing backup monitoring, restore verification, and direct follow-through on recovery drift.', 'href' => page_href('monthly-it-support-plans')],
                ['title' => 'Recovery Assessment', 'copy' => 'For owners who need to understand where ransomware and downtime risk are building before they turn into an incident.', 'href' => page_href('security-risk-assessments')],
                ['title' => 'Scoped Hardening', 'copy' => 'For access, segmentation, and recovery-critical control issues that need correction without expanding into a broad technology scope.', 'href' => page_href('network-security')],
            ],
        ],
        'services' => [
            'slug' => 'services',
            'path' => '/services',
            'nav_key' => 'services',
            'template' => 'services',
            'title' => 'Cybersecurity, Backup & Recovery Services for Small Businesses | Bald Eagle',
            'description' => 'Small-business cybersecurity, backup verification, recovery planning, and continuity monitoring services for the Salt Lake metro.',
            'hero_kicker' => 'Service Overview',
            'hero_title' => 'What Happens After the Recovery Assessment',
            'hero_intro' => 'Bald Eagle services are organized by test outcomes and recovery priorities.',
            'service_cards' => [
                ['title' => 'If Recovery Gaps Are Found', 'copy' => 'Use the Recovery Assessment to identify what fails first, what can be restored, and what has to be corrected before downtime gets expensive.', 'href' => page_href('security-risk-assessments')],
                ['title' => 'If You Need Ongoing Verification', 'copy' => 'Use monthly backup and recovery verification plans to keep backup status, restore testing, and recovery readiness from drifting back into assumptions.', 'href' => page_href('monthly-it-support-plans')],
                ['title' => 'If Ransomware Risk Is High', 'copy' => 'Apply scoped hardening for remote access, trust boundaries, and blast-radius reduction.', 'href' => page_href('network-security')],
                ['title' => 'Start Here', 'copy' => 'Start with a Recovery Assessment first. Backups are not recovery until restore testing proves it.', 'href' => page_href('security-risk-assessments')],
            ],
            'approach' => [
                'Find out what recovery actually looks like',
                'If gaps are found, use the Recovery Assessment to define the next correction',
                'If you need ongoing proof, use monthly backup and recovery verification',
                'If ransomware risk is high, harden the controls that protect recovery',
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Prove Your Backup Works'],
            'final_cta' => [
                'title' => 'Start where failure becomes visible.',
                'copy' => 'The first job is to find out what happens when systems go down. Everything after that depends on facts.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
        ],
        'terms' => [
            'slug' => 'terms',
            'path' => '/terms',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Terms of Use | Bald Eagle Network Services',
            'description' => 'Terms of use for the Bald Eagle Network Services public website.',
            'hero_kicker' => 'Terms of Use',
            'hero_title' => 'Terms for use of the public website.',
            'hero_intro' => 'These terms apply to access and use of the Bald Eagle Network Services public website.',
            'sections' => [
                [
                    'title' => 'Website Purpose',
                    'paragraphs' => [
                        'This website provides general information about services offered by Bald Eagle Network Services and a means to submit business inquiries.',
                        'Nothing on the public website guarantees service availability, project acceptance, or a specific business outcome.',
                    ],
                ],
                [
                    'title' => 'Permitted Use',
                    'paragraphs' => [
                        'You may use the website to review services, learn about service area limits, and submit a legitimate business inquiry.',
                        'You may not use the website to interfere with operations, submit abusive traffic, or attempt unauthorized access to any part of the site.',
                    ],
                ],
                [
                    'title' => 'No Client Relationship',
                    'paragraphs' => [
                        'Submitting a form or contacting Bald Eagle Network Services through the website does not by itself create a client relationship, support agreement, or project commitment.',
                        'Any engagement is subject to separate written agreement and scope approval.',
                    ],
                ],
                [
                    'title' => 'Changes',
                    'paragraphs' => [
                        'Website content and these terms may be updated from time to time without prior notice.',
                    ],
                ],
            ],
        ],
    ];

    return $definitions;
}
