<?php
declare(strict_types=1);

function site_page_definitions(): array
{
    static $definitions;

    if ($definitions !== null) {
        return $definitions;
    }

    $definitions = [
        '404' => [
            'slug' => '404',
            'path' => '/404.php',
            'nav_key' => '',
            'template' => '404',
            'title' => 'Page Not Found | Bald Eagle Network Services',
            'description' => 'The page you requested was not found.',
            'hero_kicker' => '404',
            'hero_title' => 'That page does not exist or is no longer available.',
            'hero_intro' => 'Return to the main site, review services, or send a request if you were looking for support, project help, or a security review.',
            'robots' => 'noindex,follow',
        ],
        'about' => [
            'slug' => 'about',
            'path' => '/about',
            'nav_key' => 'about',
            'template' => 'about',
            'title' => 'About Bald Eagle Network Services | Small-Business IT Continuity in Utah',
            'description' => 'Learn how Steve Carlsen helps Utah small businesses secure networks, validate backups, protect data, and keep recovery work accountable.',
            'hero_kicker' => 'About Bald Eagle',
            'hero_title' => 'Practical IT Continuity, Security, and Recovery',
            'hero_intro' => 'Bald Eagle Network Services is Steve Carlsen\'s operator-led IT continuity business for small companies that need networks secured, business data protected, backups validated, and recovery work handled directly.',
            'schema_person' => [
                'name' => 'Steve Carlsen',
                'jobTitle' => 'Founder and Operator',
                'description' => 'Steve Carlsen provides small-business IT continuity, network security, backup validation, and recovery readiness services through Bald Eagle Network Services.',
            ],
            'about_sections' => [
                [
                    'title' => 'About Bald Eagle Network Services',
                    'paragraphs' => [
                        'Bald Eagle Network Services helps small businesses prevent avoidable IT failures, protect business data, secure networks, and recover with less confusion when something breaks.',
                        'The work is practical: identify the risks that could interrupt operations, fix what can be prevented, and make sure critical systems and data are actually recoverable.',
                        'This is not a support queue model. All work is handled directly.',
                    ],
                ],
                [
                    'title' => 'Operator-Led Accountability',
                    'paragraphs' => [
                        'Steve Carlsen personally handles the work. No outsourcing. No ticket-routing layers.',
                        'You work with the person responsible for your systems. If something breaks, the same person who built or configured it is responsible for fixing it.',
                        'That keeps communication shorter, priorities clearer, and accountability visible to the business owner.',
                    ],
                ],
                [
                    'title' => 'Background and Experience',
                    'paragraphs' => [
                        'Steve has 26 years of technical operations experience across in-house environments and operator-led service delivery.',
                        'That background includes server operations, workstation and printer reliability, email and cloud administration, endpoint security, backup processes, network and firewall work, and direct user continuity support.',
                        'The goal is not to oversell specialized expertise. It is to bring long practical experience to the kinds of problems small businesses actually deal with every week.',
                    ],
                ],
                [
                    'title' => 'Prevention and Recovery Readiness',
                    'paragraphs' => [
                        'Prevention comes first because weak access, weak backups, and undocumented systems turn small problems into business interruptions.',
                        'The work centers on sensible security controls, email and cloud administration, Microsoft Defender, firewall and network hygiene, OS firewall settings, backup implementation, and restore verification processes.',
                        'The emphasis is practical risk reduction, tested recovery paths, and clear next steps instead of dramatic cybersecurity claims.',
                    ],
                ],
                [
                    'title' => 'Who This Is For',
                    'paragraphs' => [
                        'Bald Eagle is built for small businesses with roughly 5 to 20 employees that cannot justify a full internal IT department.',
                        'That often includes dental offices, law offices, contractors, and service businesses that need their systems to work without constant hand-holding.',
                        'Location coverage is centered on the Salt Lake region and Utah, with remote support handled where it makes sense and without overpromising coverage.',
                    ],
                ],
                [
                    'title' => 'How Work Is Handled',
                    'paragraphs' => [
                        'Work is scoped directly, handled directly, and communicated directly.',
                        'There is no sales handoff, no dispatcher, and no separate implementation layer. Systems are reviewed, business risk is explained plainly, priorities are set clearly, and the work moves forward without extra routing.',
                        'That approach fits businesses that want straightforward help instead of a support queue experience.',
                    ],
                ],
                [
                    'title' => 'Certifications and Tools',
                    'paragraphs' => [
                        'Current certifications include Microsoft Certified Professional (MCP) and CompTIA A+.',
                        'Net+ and Security+ are planned. Cisco certification is being considered.',
                        'Common tools and platforms include Microsoft Defender, pfSense, OS firewalls, email and cloud administration tools, and backup implementation and restore verification processes.',
                    ],
                ],
                [
                    'title' => 'Accountability',
                    'paragraphs' => [
                        'Small businesses do better when responsibility is obvious.',
                        'Bald Eagle is built around direct ownership of the work. You know who reviewed the risk, who made the recommendation, and who is responsible for follow-through.',
                        'If something breaks, the response starts with the same operator who understands the environment and the recovery path.',
                    ],
                ],
            ],
            'fit_cards' => [
                [
                    'title' => 'Direct Accountability',
                    'copy' => 'All work is handled directly by Steve Carlsen, with no outsourced queue and no handoff between layers.',
                ],
                [
                    'title' => 'Security-Aware Continuity',
                    'copy' => 'Network security, backup validation, email and data protection, and continuity support are treated as connected business risks.',
                ],
                [
                    'title' => 'Small-Business Fit',
                    'copy' => 'Small businesses with 5-20 employees that need accountable support but do not need a full internal IT department.',
                ],
            ],
            'secondary_cta' => [
                'href' => page_href('services'),
                'label' => 'View Services',
            ],
            'final_cta' => [
                'title' => 'Start with a Recovery Assessment before the next failure sets the priority.',
                'copy' => 'Review what is protected, what is exposed, what has been tested, and what would actually be recoverable if systems, access, or business data failed.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
            'related_links' => ['security-risk-assessments', 'monthly-it-support-plans', 'backup-disaster-recovery'],
        ],
        'backup-disaster-recovery' => [
            'slug' => 'backup-disaster-recovery',
            'path' => '/backup-disaster-recovery',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Backup & Recovery Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Backup and recovery services in Salt Lake City for businesses that need verified restores and practical continuity planning.',
            'hero_kicker' => 'Backup & Disaster Recovery',
            'hero_title' => 'Backup, Recovery, and Restore Confidence',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses monitor backups, verify restores, and shorten recovery time when ransomware, deletion, or system failure hits.',
            'card_title' => 'Backup & Disaster Recovery',
            'card_copy' => 'Backup monitoring, restore testing, retention review, and recovery planning tied to business continuity.',
            'pain_points' => [
                'Backups appear healthy but no one knows whether key data can actually be restored',
                'Retention settings do not reflect operational downtime or legal needs',
                'Critical systems have no documented order of recovery after an incident',
                'Ransomware planning stops at backup status instead of restore readiness',
            ],
            'included' => [
                'Backup configuration and monitoring review',
                'Recovery priorities aligned to business operations',
                'Restore testing guidance or supervised execution',
                'Continuity recommendations tied to actual systems and dependencies',
            ],
            'who_for_title' => 'For offices that cannot absorb data loss or long downtime.',
            'who_for_copy' => 'This service fits small professional-service businesses and local offices that rely on file access, account access, line-of-business systems, or shared data to stay open.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'When recovery planning is vague, incident response becomes guesswork. That extends downtime and turns manageable failures into business-wide disruption.',
                'Verified restores create a more honest continuity plan because owners can see what recovery would actually require before a real incident forces the answer.',
            ],
            'deliverables' => [
                'Backup and recovery posture review',
                'Prioritized restore and continuity concerns',
                'Retention, monitoring, and restoration recommendations',
                'Defined next steps for remediation or ongoing continuity oversight',
            ],
            'cta_title' => 'If you have never restored it, you do not know if it comes back.',
            'cta_copy' => 'Most backups exist but are never tested. Start with the system that would stop the business first.',
            'contact_service_type' => 'backup-dr',
            'primary_cta_label' => 'Prove Your Backup Works',
            'process_heading' => 'How backup verification turns into a real recovery plan.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Review', 'copy' => 'Identify the backups, systems, and restore assumptions tied to your highest downtime risk.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Confirm what can be restored, what is untested, and where ransomware pressure would break the plan.'],
                ['step' => '03', 'title' => 'Prioritize', 'copy' => 'Deliver the next actions for restore testing, retention fixes, and continuity improvements.'],
            ],
            'secondary_cta' => ['href' => page_href('services'), 'label' => 'View All Services'],
            'related_links' => ['services', 'security-risk-assessments', 'case-study-backup-recovery-failure', 'monthly-it-support-plans'],
        ],
        'compliance-readiness' => [
            'slug' => 'compliance-readiness',
            'path' => '/compliance-readiness',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Compliance Readiness Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Continuity and control readiness services in Salt Lake City for small businesses preparing for audits, insurance reviews, or client pressure.',
            'hero_kicker' => 'Compliance Readiness',
            'hero_title' => 'Compliance Readiness Support',
            'hero_intro' => 'Bald Eagle helps Salt Lake City businesses prepare for audits and client reviews by tightening controls, documentation, access standards, and device discipline.',
            'card_title' => 'Compliance Readiness',
            'card_copy' => 'Control cleanup and remediation support ahead of audits, questionnaires, and client reviews.',
            'pain_points' => [
                'Client or insurance questionnaires exposing weak answers',
                'No documented control owner for key security areas',
                'Account access and endpoint settings that are inconsistent',
                'Too much scrambling right before a review or renewal',
            ],
            'included' => [
                'Gap review against stated readiness needs',
                'Control cleanup recommendations and remediation support',
                'Documentation assistance for current-state explanations',
                'Alignment between support work, security work, and audit pressure',
            ],
            'who_for_title' => 'For businesses preparing for outside scrutiny.',
            'who_for_copy' => 'This service fits organizations that are facing a client security review, insurance requirement, compliance checklist, or internal pressure to clean up control issues before they become expensive.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Compliance pressure often reveals operational weaknesses that already exist. Waiting until the deadline usually makes remediation more expensive and more disruptive.',
                'Readiness work gives owners a more controlled way to fix the basics, document the environment, and stop guessing about what is actually missing.',
            ],
            'deliverables' => [
                'Readiness gap summary',
                'Control remediation priorities',
                'Implementation support recommendations',
                'Defined path into project work or monthly support if needed',
            ],
            'cta_title' => 'If controls break under pressure, recovery breaks with them.',
            'cta_copy' => 'Start with the weakest control, the audit pressure, or the requirement your business cannot defend today.',
            'contact_service_type' => 'compliance',
            'primary_cta_label' => 'Identify Gaps in Your Backup and Recovery Process',
            'process_heading' => 'How readiness work moves from outside pressure to practical fixes.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Identify', 'copy' => 'Review the questionnaire, insurance demand, or audit pressure revealing the current gap.'],
                ['step' => '02', 'title' => 'Map', 'copy' => 'Tie the control weakness to recovery, access, or continuity risk inside the real environment.'],
                ['step' => '03', 'title' => 'Close', 'copy' => 'Return a prioritized remediation path with the documentation or cleanup steps that matter first.'],
            ],
            'secondary_cta' => ['href' => page_href('network-security'), 'label' => 'Review Network Security'],
            'related_links' => ['network-security', 'security-risk-assessments', 'services'],
        ],
        'contact' => [
            'slug' => 'contact',
            'path' => '/contact',
            'nav_key' => 'contact',
            'template' => 'contact',
            'title' => 'Request a Recovery Assessment | Salt Lake Metro | Bald Eagle',
            'description' => 'Request a Recovery Assessment for your Salt Lake metro business and identify backup, recovery, and ransomware weaknesses before downtime does.',
            'hero_kicker' => 'Risk Assessment Request',
            'hero_title' => 'Request a Recovery Assessment',
            'hero_intro' => 'Use this short form to start a Recovery Assessment. It checks whether your backups, restore process, and failure response are actually usable.',
            'contact_points' => [
                'Name the system, data set, or workflow your team cannot lose',
                'Tell us when you last completed a successful restore test',
                'Flag whether ransomware, downtime, or account access is the bigger concern',
                'Share any looming deadline such as insurance, audit, or client pressure',
                'Keep it short if needed; the goal is to identify the next review step quickly',
            ],
            'response_points' => [
                'Direct response with defined scope and next action',
                'Requests filtered to Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Recommendation for assessment findings, backup verification, recovery planning, or continuity monitoring',
                'No ticket maze and no outsourced sales handoff',
            ],
            'form_title' => 'Start a Recovery Assessment',
            'form_copy' => 'If you have never restored your data, you do not know whether you have a backup. A Recovery Assessment shows what works and what fails.',
        ],
        'faq' => [
            'slug' => 'faq',
            'path' => '/faq',
            'nav_key' => '',
            'template' => 'faq',
            'title' => 'Recovery Assessment FAQ | Bald Eagle Network Services',
            'description' => 'Answers about Recovery Assessments, backup recovery risk, restore testing, and Salt Lake metro service fit.',
            'hero_kicker' => 'Frequently Asked Questions',
            'hero_title' => 'Recovery Assessment FAQ',
            'hero_intro' => 'These answers cover fit, assessment scope, backup validation, restore testing, and local coverage in the Salt Lake metro.',
            'faq_items' => [
                ['question' => 'What size company is the best fit?', 'answer' => 'The public site is written for small professional-service businesses and local offices with roughly 5 to 20 employees that depend on continuity but do not have deep internal IT coverage.'],
                ['question' => 'Do you only support businesses in Salt Lake?', 'answer' => 'Yes. Service is limited to the Salt Lake metro and nearby businesses within about a 30-mile radius.'],
                ['question' => 'Can we start with an assessment instead of ongoing service?', 'answer' => 'Yes. Most engagements begin with a Recovery Assessment to establish facts before discussing remediation or monitoring.'],
                ['question' => 'Do you provide broad day-to-day coverage for every system issue?', 'answer' => 'The public site is intentionally focused on backup and recovery outcomes, recovery testing, continuity planning, and scoped security work that protects those outcomes.'],
                ['question' => 'What does continuity monitoring cover?', 'answer' => 'Continuity monitoring is limited oversight tied to backup health, recovery readiness, retention concerns, and follow-through on issues that would materially affect downtime or restore success.'],
                ['question' => 'Do you handle account access and endpoint issues?', 'answer' => 'Yes, but only where those systems affect recovery speed, identity protection, file access, or business continuity. The goal is not broad platform administration for its own sake.'],
                ['question' => 'Can you help with security hardening?', 'answer' => 'Yes, in a scoped way. Hardening work is aimed at reducing blast radius, tightening access, and protecting recovery paths rather than turning the engagement into a broad network security program.'],
                ['question' => 'What happens after we submit the form?', 'answer' => 'The request is reviewed for fit, urgency, and service area. You get a direct response with the best next step and scope for the assessment.'],
            ],
            'final_cta' => [
                'title' => 'Stop guessing what happens when systems fail.',
                'copy' => 'Talk directly to the operator and find out what recovery actually looks like in your environment.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
        ],
        'home' => [
            'slug' => 'home',
            'path' => '/',
            'nav_key' => 'services',
            'template' => 'home',
            'title' => 'Small Business IT Continuity, Network Security & Backup Recovery in Salt Lake City | Bald Eagle',
            'description' => 'Bald Eagle helps Salt Lake small businesses prevent IT failures, secure networks, protect email and business data, and recover quickly when systems break.',
            'hero_kicker' => 'Salt Lake Small Business IT Continuity',
            'hero_title' => 'Keep your business running when technology fails.',
            'hero_intro' => 'Bald Eagle helps small businesses prevent avoidable IT failures, protect business data, secure networks, and recover quickly when something breaks.',
            'hero_panel_label' => 'What We Help Protect',
            'trust_points' => [
                'Business data and shared files',
                'Email, identity, and account access',
                'Office networks, firewalls, and remote access',
                'Backups, restores, and continuity plans',
            ],
            'secondary_cta' => ['href' => page_href('services'), 'label' => 'View Services'],
            'trust_strip' => [
                'Network security',
                'Backup and recovery',
                'Email and data protection',
                'IT continuity support',
                'Salt Lake small-business focus',
            ],
            'core_services' => [
                [
                    'title' => 'Network Security',
                    'copy' => 'Secure firewalls, remote access, account boundaries, and network changes so one weak point does not put the whole office at risk.',
                    'href' => page_href('network-security'),
                    'link_label' => 'Review Network Security',
                ],
                [
                    'title' => 'Backup & Disaster Recovery',
                    'copy' => 'Review backup scope, restore steps, retention, and recovery order before downtime turns into a larger business problem.',
                    'href' => page_href('backup-disaster-recovery'),
                    'link_label' => 'Review Backup & Recovery',
                ],
                [
                    'title' => 'Email & Data Protection',
                    'copy' => 'Protect email, shared files, cloud data, and access paths that owners depend on every day.',
                    'href' => page_href('services'),
                    'link_label' => 'View Data Protection Services',
                ],
                [
                    'title' => 'IT Continuity Support',
                    'copy' => 'Keep small-office systems documented, monitored, and easier to recover when hardware, access, or data problems interrupt work.',
                    'href' => page_href('monthly-it-support-plans'),
                    'link_label' => 'Review Continuity Support',
                ],
            ],
            'founder_section' => [
                'eyebrow' => 'Direct Technical Ownership',
                'title' => 'Practical IT Continuity for Owner-Led Businesses',
                'paragraphs' => [
                    'Bald Eagle Network Services is built for Salt Lake small businesses that need their network, email, files, backups, and core systems to stay usable.',
                    'The work is direct and owner-focused: identify the failure points, secure the systems that carry business data, and define what recovery would actually require.',
                    'The goal is not a broad technology catalog. It is practical continuity work for businesses that need fewer surprises and clearer next steps.',
                ],
                'card_title' => 'What That Means',
                'card_points' => [
                    'Network and access decisions tied to business risk',
                    'Backups reviewed for recovery, not just status',
                    'Email and file protection treated as continuity work',
                ],
                'cta_href' => page_href('about'),
                'cta_label' => 'About Bald Eagle',
            ],
            'warning_signs' => [
                [
                    'title' => 'Small failures are interrupting normal work',
                    'copy' => 'Recurring network, access, printer, file, or email issues often point to weak documentation, unclear ownership, or systems that have drifted over time.',
                ],
                [
                    'title' => 'Backups exist, but recovery is uncertain',
                    'copy' => 'A backup job can report green while restore steps, data coverage, permissions, and recovery order remain untested.',
                ],
                [
                    'title' => 'Email and shared files carry too much risk',
                    'copy' => 'Old access, weak account controls, scattered cloud files, and unclear ownership make business data harder to protect and harder to recover.',
                ],
                [
                    'title' => 'One system outage can stop the office',
                    'copy' => 'If no one knows what depends on what, a firewall issue, server problem, account lockout, or data loss can become a full business interruption.',
                ],
            ],
            'why_cards' => [
                [
                    'title' => 'Start with a Recovery Assessment',
                    'copy' => 'The first step is to identify the systems, data, access paths, and backup assumptions that could interrupt the business.',
                ],
                [
                    'title' => 'Fix the risks that interrupt work',
                    'copy' => 'Recommendations stay tied to continuity, network security, backup recovery, and protection of business data.',
                ],
                [
                    'title' => 'Keep the scope practical',
                    'copy' => 'The work is sized for Salt Lake small businesses that need clear action, not generic MSP packaging or a promise to do everything IT.',
                ],
            ],
            'proof_strip' => [
                [
                    'title' => 'Prevent avoidable IT failures',
                    'copy' => 'Reduce the drift that causes outages: undocumented changes, weak access control, aging assumptions, and untested recovery steps.',
                ],
                [
                    'title' => 'Protect business data',
                    'copy' => 'Treat email, files, permissions, backups, and cloud data as part of the same continuity plan.',
                ],
                [
                    'title' => 'Recover quickly when something breaks',
                    'copy' => 'Know what has to come back first, what can be restored, and what needs to be corrected before a real failure.',
                ],
            ],
            'case_study_block' => [
                'eyebrow' => 'Continuity Risk Example',
                'title' => 'Backups Help Only If Recovery Works',
                'paragraphs' => [
                    'A small office had backups in place, but the restore process had not been tested. When recovery was reviewed, missing data, unclear steps, and permission issues appeared before a real outage exposed them.',
                    'That is the kind of risk a Recovery Assessment is meant to find: not just whether tools exist, but whether the business can keep operating and recover usable data.',
                ],
                'card_title' => 'Backup Existed. Recovery Failed.',
                'card_copy' => 'A backup system was present, but recovery assumptions broke when restore behavior was checked.',
                'points' => [
                    'Backup scope did not match business data',
                    'Restore steps were not documented clearly',
                    'Permissions did not come back cleanly',
                    'Recurring verification was needed',
                ],
                'href' => page_href('case-study-backup-recovery-failure'),
                'label' => 'Read the Case Study',
                'secondary_href' => page_href('case-study-security-recovery-failure'),
                'secondary_label' => 'Read the Security Exposure Example',
            ],
            'engagements' => [
                [
                    'title' => 'If You Need Baseline Protection',
                    'copy' => 'Use a Recovery Assessment to find the network, backup, email, file, and access risks most likely to interrupt the business.',
                    'points' => [
                        'Network and access review',
                        'Backup and data protection checks',
                        'Clear next actions for continuity risk',
                    ],
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Start a Recovery Assessment',
                ],
                [
                    'title' => 'If You Need Ongoing Continuity Support',
                    'copy' => 'Use monthly verification and continuity support to keep backup status, restore readiness, and protection gaps from drifting back into assumptions.',
                    'points' => [
                        'Backup and restore follow-through',
                        'Continuity issue tracking',
                        'Practical support for small-office systems',
                    ],
                    'href' => page_href('monthly-it-support-plans'),
                    'link_label' => 'Review Continuity Support',
                ],
            ],
            'access_control' => [
                'title' => 'Email and cloud data protection are part of the continuity plan.',
                'copy' => 'Microsoft 365, Outlook/Exchange, OneDrive, SharePoint, and cloud files are supporting systems owners rely on every day. They need access control, backup awareness, and recovery planning like any other business-critical system.',
                'points' => [
                    'Email and account access review',
                    'Shared file and cloud data dependency checks',
                    'Administrative boundary cleanup',
                    'Protection steps tied to business continuity',
                ],
            ],
            'service_area' => [
                'title' => 'Focused on Salt Lake small businesses.',
                'copy' => 'Bald Eagle works with small businesses in the Salt Lake metro that need practical IT continuity, network security, backup recovery, and data protection support.',
                'points' => [
                    'Salt Lake City and nearby business corridors',
                    'Practical on-site follow-through when needed',
                    'Owner-focused communication',
                    'Small-business scope and priorities',
                ],
            ],
            'process' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Review the systems, network, email, data, and backup dependencies that keep the business running.'],
                ['step' => '02', 'title' => 'Prioritize', 'copy' => 'Separate routine cleanup from the risks most likely to cause downtime, data loss, or recovery delays.'],
                ['step' => '03', 'title' => 'Protect', 'copy' => 'Tighten network security, access controls, backup coverage, and data protection where the risk is real.'],
                ['step' => '04', 'title' => 'Recover', 'copy' => 'Document what comes back first and what has to be verified before the next failure tests the plan.'],
            ],
            'faq_items' => [
                [
                    'question' => 'Do you only work with companies in Salt Lake?',
                    'answer' => 'Yes. The public site is intentionally limited to the Salt Lake metro and nearby businesses within roughly 30 miles.',
                ],
                [
                    'question' => 'What is a Recovery Assessment?',
                    'answer' => 'It is a practical review of the systems, data, network controls, backups, and recovery assumptions that determine whether the business can keep working or recover quickly after a failure.',
                ],
                [
                    'question' => 'Do you help protect email and cloud files?',
                    'answer' => 'Yes. Email, account access, shared files, and cloud data are reviewed where they affect business continuity, data protection, and recovery.',
                ],
                [
                    'question' => 'What kinds of businesses are the best fit?',
                    'answer' => 'Small owner-led businesses and local offices with roughly 5 to 20 employees that rely on their network, email, business files, and backups to keep operating.',
                ],
            ],
            'final_cta' => [
                'title' => 'Start with a Recovery Assessment.',
                'copy' => 'Find the network, backup, email, data, and continuity risks that could interrupt the business before they become expensive surprises.',
            ],
        ],
        'monthly-it-support-plans' => [
            'slug' => 'monthly-it-support-plans',
            'path' => '/monthly-it-support-plans',
            'nav_key' => 'plans',
            'template' => 'commercial',
            'title' => 'Monthly Backup and Recovery Verification Plans | Bald Eagle Network Services',
            'description' => 'Monthly backup monitoring, restore verification, and recovery readiness oversight for small businesses that need proof their systems can be recovered.',
            'hero_kicker' => 'Ongoing Recovery Verification',
            'hero_title' => 'Monthly Backup and Recovery Verification Plans',
            'hero_intro' => 'These plans provide ongoing backup monitoring, restore verification, recovery readiness review, and failure-response preparation for small businesses that cannot afford to discover problems during an outage.',
            'card_title' => 'Monthly Backup and Recovery Verification',
            'card_copy' => 'Monthly backup monitoring, restore verification, and recovery follow-through tied to real failure conditions.',
            'pain_points' => [
                'Backup jobs report success but nobody is checking whether protected systems can actually be restored',
                'Restore testing gets delayed until an outage, audit, or ransomware event forces the issue',
                'Recovery gaps stay open because nobody is reviewing them month to month',
                'Owners need steady visibility into backup health without turning the work into a general IT contract',
            ],
            'included' => [
                'Backup job monitoring and exception review',
                'Restore verification scheduling and follow-through',
                'Monthly review of recovery blockers, retention concerns, and readiness drift',
                'Failure-response preparation tied to the systems that matter first',
            ],
            'who_for_title' => 'For companies that need recovery verified, not assumed.',
            'who_for_copy' => 'These plans fit businesses that already know backup and recovery cannot be left to a dashboard, a vendor promise, or an annual panic review.',
            'why_title' => 'Why restore testing matters',
            'why_paragraphs' => [
                'Backup status alone does not prove recoverability. Restore testing is what shows whether the data is usable, whether the process works, and whether the business could actually get back online under pressure.',
                'Monthly verification keeps backup and recovery from drifting back into assumptions after the initial assessment is done.',
            ],
            'deliverables' => [
                'Monthly summary of backup status, verification results, and unresolved recovery risks',
                'Restore testing follow-through on the systems that matter first',
                'Clear notice when backup or recovery gaps are found',
                'Defined next actions for remediation, hardening, or another Recovery Assessment review',
            ],
            'cta_title' => 'When backup verification stops, recovery drifts back into guesswork.',
            'cta_copy' => 'Start with a Recovery Assessment. The monthly plan only works when the business knows what must be protected, what has to be restored first, and what still fails under pressure.',
            'contact_service_type' => 'monthly-backup-verification',
            'primary_cta_label' => 'Request a Recovery Assessment',
            'process_heading' => 'How monthly backup and recovery verification works.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Monitor', 'copy' => 'Review backup health, failures, missed jobs, and retention concerns tied to business-critical systems.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Check whether restore testing is current, whether the last result proved anything useful, and where recovery confidence is still weak.'],
                ['step' => '03', 'title' => 'Respond', 'copy' => 'When backup or recovery gaps are found, define the fix path quickly instead of letting the issue sit until the next outage.'],
            ],
            'secondary_cta' => ['href' => page_href('services'), 'label' => 'View All Services'],
            'related_links' => ['services', 'security-risk-assessments', 'backup-disaster-recovery'],
        ],
        'network-security' => [
            'slug' => 'network-security',
            'path' => '/network-security',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Scoped Security Hardening in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Scoped security hardening in Salt Lake City for businesses that need better access control, reduced blast radius, and stronger recovery outcomes.',
            'hero_kicker' => 'Security Hardening',
            'hero_title' => 'Scoped Security Hardening',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses tighten the controls that most affect ransomware resilience, recovery speed, and continuity risk.',
            'card_title' => 'Scoped Security Hardening',
            'card_copy' => 'Targeted hardening for identity, remote access, segmentation, and recovery-critical systems.',
            'pain_points' => [
                'Remote access or identity controls would make a recovery event harder to contain',
                'Flat networks and broad permissions create too much blast radius',
                'Security changes were made reactively and never cleaned up',
                'Critical systems lack the access boundaries needed for credible continuity planning',
            ],
            'included' => [
                'Identity, remote access, and edge control review',
                'Segmentation or trust-boundary recommendations where needed',
                'Scoped corrective hardening aligned to continuity priorities',
                'Recommendations that support backup and recovery outcomes',
            ],
            'who_for_title' => 'For businesses that know their controls are too loose to trust during an incident.',
            'who_for_copy' => 'This service is for companies that need practical hardening to support recovery outcomes, not a broad network security program or enterprise theater.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Small business recovery gets harder when identity, remote access, and internal trust boundaries are loose. Weak controls increase both the chance of compromise and the scope of disruption.',
                'Hardening here is about removing easy mistakes, tightening trust boundaries, and protecting the systems that would matter most during recovery.',
            ],
            'deliverables' => [
                'Current-state hardening review',
                'Prioritized corrective actions',
                'Access, segmentation, or control recommendations',
                'Clear next-step plan for remediation work',
            ],
            'cta_title' => 'If ransomware gets in, how far does it spread before you stop it?',
            'cta_copy' => 'Bring the entry point, trust boundary, or control gap that would fail under pressure.',
            'contact_service_type' => 'network-security',
            'primary_cta_label' => 'Assess Your Exposure to Ransomware Spread',
            'process_heading' => 'How targeted hardening work stays tied to resilience instead of bloat.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Identify the identity, remote access, or trust-boundary weakness raising ransomware exposure.'],
                ['step' => '02', 'title' => 'Contain', 'copy' => 'Define the control changes that reduce blast radius without expanding scope into a generic overhaul.'],
                ['step' => '03', 'title' => 'Validate', 'copy' => 'Confirm the hardening actions support backup recovery, continuity, and incident containment goals.'],
            ],
            'secondary_cta' => ['href' => page_href('services'), 'label' => 'View All Services'],
            'related_links' => ['services', 'security-risk-assessments', 'case-study-security-recovery-failure'],
        ],
        'privacy-policy' => [
            'slug' => 'privacy-policy',
            'path' => '/privacy-policy',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Privacy Policy | Bald Eagle Network Services',
            'description' => 'Privacy policy for the Bald Eagle Network Services public website and contact request form.',
            'hero_kicker' => 'Privacy Policy',
            'hero_title' => 'How contact requests and site data are handled.',
            'hero_intro' => 'This privacy policy applies to the public website for Bald Eagle Network Services and explains the limited data collected through contact requests.',
            'sections' => [
                [
                    'title' => 'Information Collected',
                    'paragraphs' => [
                        'The public website collects the information you submit through the contact form, including name, company, email address, phone number, preferred contact method, employee count, main concern, assessment type, and message content.',
                        'Basic technical request information such as IP address and browser user agent may also be logged for security, abuse prevention, and troubleshooting.',
                    ],
                ],
                [
                    'title' => 'How Information Is Used',
                    'paragraphs' => [
                        'Submitted information is used to review service fit, respond to inquiries, and manage follow-up related to recovery testing, continuity monitoring, remediation projects, or related support requests.',
                        'Information is not sold or rented through the public website.',
                    ],
                ],
                [
                    'title' => 'Security and Retention',
                    'paragraphs' => [
                        'Reasonable administrative and technical safeguards are used on the public website, including CSRF protection, validation, and anti-abuse controls on the contact form.',
                        'Inquiry data is retained only as long as needed for business communication, recordkeeping, and security review.',
                    ],
                ],
                [
                    'title' => 'Contact',
                    'paragraphs' => [
                        'Questions about this privacy policy can be submitted through the public contact form.',
                    ],
                ],
            ],
        ],
        'security-risk-assessments' => [
            'slug' => 'security-risk-assessments',
            'path' => '/recovery-assessment',
            'nav_key' => 'services',
            'template' => 'recovery-assessment',
            'title' => 'Recovery Assessment | Backup & Recovery Review | Bald Eagle Network Services Utah',
            'description' => 'Structured backup and recovery review for Utah small businesses. Verify what is backed up, what restores, and what fails before an outage.',
            'hero_kicker' => 'Primary Conversion Path',
            'hero_title' => 'Recovery Assessment',
            'hero_intro' => 'If everything fails, your systems can be recovered, but only if recovery has been tested and proven.',
            'hero_paragraphs' => [
                'This is a structured review of backup and recovery capability for small businesses that cannot afford to guess during an outage.',
                'The focus is real-world failure, not configuration assumptions, vendor dashboards, or backup jobs that only look healthy on paper.',
            ],
            'card_title' => 'Recovery Assessment',
            'card_copy' => 'Structured backup and recovery review focused on what actually fails, what restores, and what has to be fixed first.',
            'assessment_standard' => [
                'Backup success is not treated as proof of recovery.',
                'Documented restore steps matter because pressure exposes missing process fast.',
                'Security weaknesses that slow or block recovery are part of the review.',
            ],
            'what_this_is' => [
                'A Recovery Assessment is a direct review of whether your backup and recovery process can hold up when systems actually fail.',
                'It checks what is being protected, what is missing, what restore process exists, and whether the business could keep operating under real pressure.',
                'If recovery has not been tested, it is not considered reliable.',
            ],
            'what_is_checked_cards' => [
                [
                    'title' => 'Backup Scope',
                    'copy' => 'Check what systems are currently backed up and whether business-critical servers, files, cloud data, and line-of-business systems are actually included.',
                ],
                [
                    'title' => 'Data Coverage',
                    'copy' => 'Review what data is protected, what is excluded, and whether the gaps are known or only discovered after a failure.',
                ],
                [
                    'title' => 'Backup Completion',
                    'copy' => 'Confirm whether backup jobs are completing successfully and whether failures are being seen, ignored, or hidden by bad assumptions.',
                ],
                [
                    'title' => 'Restore Process',
                    'copy' => 'Check whether a restore process exists, whether it is documented, and whether anyone could follow it under pressure.',
                ],
                [
                    'title' => 'Restore Testing',
                    'copy' => 'Review whether a restore has ever been tested, what was tested, and whether the result proved anything useful.',
                ],
                [
                    'title' => 'Recovery Time',
                    'copy' => 'Estimate how long recovery would actually take based on dependencies, order of operations, and what has to come back first.',
                ],
                [
                    'title' => 'Destructive Events',
                    'copy' => 'Measure exposure to ransomware, deletion, corruption, and other destructive events that turn backup assumptions into business downtime.',
                ],
                [
                    'title' => 'Access Risk',
                    'copy' => 'Review administrative access, shared credentials, identity risk, and control failures that directly affect recovery speed or containment.',
                ],
            ],
            'what_you_get' => [
                'Clear breakdown of current backup coverage',
                'Identified gaps in recovery capability',
                'Realistic recovery expectations instead of assumptions',
                'Prioritized list of what needs to be fixed first',
                'Plain-language explanation of the risks',
            ],
            'what_you_get_copy' => [
                'The output is meant to be usable. It shows what is covered, what is missing, what probably fails under pressure, and what deserves immediate attention.',
                'It is written so an owner can understand the operational risk without needing a vendor translation layer.',
            ],
            'what_happens_after' => [
                'Findings are reviewed directly with Steve Carlsen, not handed off to a different person after the assessment is finished.',
                'Critical gaps are addressed first, recovery process is corrected where needed, and restore testing is performed when the business is relying on assumptions.',
                'If the environment needs follow-through, ongoing validation can be set up without turning the work into a support-queue relationship.',
            ],
            'after_steps' => [
                'Findings reviewed directly with Steve Carlsen',
                'Critical recovery gaps addressed first',
                'Recovery process implemented or corrected',
                'Restore testing performed where needed',
                'Ongoing validation set up if justified',
                'No handoff and no escalation layers',
            ],
            'what_this_is_not_copy' => [
                'This is not a paper review. Systems are evaluated based on what actually happens when something fails.',
                'The point is to identify whether recovery works, not to produce a checklist that avoids hard questions.',
            ],
            'what_this_is_not' => [
                'Not a generic IT audit',
                'Not a checklist exercise',
                'Not a sales presentation',
                'Not based on assumptions or vendor claims',
            ],
            'why_this_matters_cards' => [
                [
                    'title' => 'Most Backups Are Never Tested',
                    'copy' => 'Many businesses only find out a restore fails when an outage is already happening and time is already lost.',
                ],
                [
                    'title' => 'Pressure Exposes Weak Recovery',
                    'copy' => 'Recovery failures show up when people are rushed, access is broken, documentation is missing, and the restore order was never thought through.',
                ],
                [
                    'title' => 'Downtime Does The Damage',
                    'copy' => 'The real cost shows up when systems stay down, staff stop working, and critical data is unavailable longer than expected.',
                ],
                [
                    'title' => 'Security And Recovery Are Connected',
                    'copy' => 'Weak admin controls, ransomware spread, and poor access discipline directly affect whether recovery is possible and how long it takes.',
                ],
            ],
            'why_this_matters_copy' => [
                'When systems fail, recovery is what determines whether the business continues operating.',
            ],
            'proof_block' => [
                'eyebrow' => 'Proof Of Work',
                'title' => 'Real Example: Backup Existed. Recovery Failed.',
                'paragraphs' => [
                    'One small office had backups in place, no obvious alerts, and every reason to assume recovery would work.',
                    'The recovery test showed missing data, broken permissions, no documented restore process, and recovery time expectations that were not grounded in reality.',
                    'A second case study demonstrates how weak access control can expose backup systems to destructive actions and break recovery entirely.',
                ],
                'card_eyebrow' => 'Case Study #1',
                'card_title' => 'Backup Existed. Recovery Failed.',
                'card_copy' => 'See what was found, what failed during restore testing, and what had to be corrected before the business could rely on recovery.',
                'href' => page_href('case-study-backup-recovery-failure'),
                'label' => 'Read the Recovery Failure Example',
                'secondary_href' => page_href('case-study-security-recovery-failure'),
                'secondary_label' => 'Read the Security Exposure Example',
            ],
            'submission_clarity' => [
                'title' => 'What Happens After You Submit',
                'points' => [
                    'You will receive a direct response within one business day.',
                    'You will hear directly from Steve Carlsen.',
                    'Your situation is reviewed first, clarification questions are asked if needed, and the next step is then scheduled.',
                    'This is not a sales call, not a generic consultation, and not outsourced.',
                ],
                'what_you_get_title' => 'What You Will Get',
                'what_you_get' => [
                    'Clear understanding of recovery capability',
                    'Identification of failure points',
                    'Prioritized next steps',
                ],
                'trust_line' => 'You are not handed off. The same person reviewing your systems is responsible for fixing them.',
            ],
            'contact_service_type' => 'risk-assessment',
            'primary_cta_label' => 'Start a Recovery Assessment',
            'secondary_cta' => ['href' => page_href('contact'), 'label' => 'Contact Bald Eagle'],
            'cta_supporting_line' => 'Find out what actually happens when your systems fail.',
            'related_links' => ['services', 'backup-disaster-recovery', 'monthly-it-support-plans', 'network-security', 'contact'],
        ],
        'case-study-backup-recovery-failure' => [
            'slug' => 'case-study-backup-recovery-failure',
            'path' => '/case-study-backup-recovery-failure',
            'nav_key' => 'case-study-backup-recovery-failure',
            'template' => 'case-study',
            'title' => 'Case Study: Backup Existed, Recovery Failed | Bald Eagle Network Services',
            'description' => 'A small-business backup failure pattern showing why restore testing, backup scope, and recovery readiness matter before downtime starts.',
            'hero_kicker' => 'Case Study #1',
            'hero_title' => 'Backup Was Running. Recovery Was Not Ready.',
            'hero_intro' => 'Backup is not continuity until restore testing proves that business data, permissions, and recovery steps work.',
            'card_title' => 'Backup Existed. Recovery Failed.',
            'card_copy' => 'A recovery test exposed missing data, broken restore steps, and backup assumptions that would have become business downtime.',
            'situation' => [
                'A small office believed the environment was protected because backup jobs were running and no obvious alerts were being reported.',
                'The failure was in readiness. No one had tested a full restore, confirmed which business data was included, or documented what would happen if a drive, server, sync process, or ransomware event forced recovery during business hours.',
                'For the owner, the business impact was not technical. It was lost operating time, uncertainty about which files could come back, and no clear answer for employees waiting to work.',
            ],
            'what_was_wrong' => [
                'Backup scope had not been checked against business-critical files and systems',
                'Key data locations and dependencies were not clearly mapped',
                'No documented restore process existed for a real outage',
                'No one had performed a restore test before recovery was needed',
                'Recovery time expectations were based on hope instead of evidence',
            ],
            'what_failed_eyebrow' => 'Protection Gap',
            'what_failed_title' => 'What Should Have Been Protected',
            'what_failed' => [
                'Business-critical files, shared folders, and working data locations',
                'File structure and permissions needed for normal operations',
                'Line-of-business data, system dependencies, and recovery order',
                'A restore process with realistic timing and clear ownership',
            ],
            'what_was_fixed' => [
                'Mapped business-critical data and systems into the backup scope review',
                'Checked backup completion, consistency, retention, and recovery points',
                'Defined restore steps so recovery did not depend on memory under pressure',
                'Performed practical restore testing where appropriate',
                'Set recovery expectations based on what the restore path could actually support',
                'Added recurring verification so backup readiness did not become a one-time assumption',
            ],
            'why_it_mattered' => [
                'The business was not deciding between good and bad backup software. It was relying on backup status as if it proved recovery capability.',
                'If a real outage or ransomware event had forced the first restore test, the owner would have discovered missing data, permissions problems, and unclear steps while downtime was already costing time and money.',
                'Backup testing turns a hidden operational risk into a known recovery path.',
            ],
            'outcome_title' => 'Recovery readiness replaced backup assumptions.',
            'outcome' => [
                'The practical improvement was a recovery path the owner could understand: what was protected, what still needed attention, how restore steps worked, and where recovery timing was realistic.',
                'That changed the conversation from hoping the backup job was enough to knowing what recovery would actually require before the next failure.',
            ],
            'check_cards' => [
                [
                    'title' => 'Check Backup Scope',
                    'copy' => 'Confirm the files, systems, and cloud data locations that matter most are actually included. Green backup status does not prove complete coverage.',
                ],
                [
                    'title' => 'Check Restore Steps',
                    'copy' => 'If no one can describe the restore process under pressure, recovery is still guesswork.',
                ],
                [
                    'title' => 'Check A Real Restore',
                    'copy' => 'Test whether files, folders, permissions, and application data come back in a usable state.',
                ],
                [
                    'title' => 'Check Recovery Time',
                    'copy' => 'Compare assumed recovery time to what the restore actually takes when dependencies and missing steps get involved.',
                ],
            ],
            'cta' => [
                'title' => 'Start with a Recovery Assessment.',
                'copy' => 'If no one has tested a restore in your environment, the next outage may become the first real proof of what is missing.',
                'label' => 'Start a Recovery Assessment',
                'href' => recovery_assessment_href('backup-recovery-failure', 'contact-form'),
            ],
            'mid_cta' => [
                'eyebrow' => 'Recovery Readiness',
                'title' => 'Validate Recovery Before Downtime Decides It',
                'copy' => 'Treat this example as a warning: test restore behavior before a real outage, failed drive, deleted file, or ransomware event forces the test.',
                'label' => 'Start a Recovery Assessment',
                'href' => recovery_assessment_href('backup-recovery-failure', 'contact-form'),
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Review Backup & Disaster Recovery'],
            'related_links' => ['backup-disaster-recovery', 'security-risk-assessments', 'services'],
        ],
        'case-study-security-recovery-failure' => [
            'slug' => 'case-study-security-recovery-failure',
            'path' => '/case-study-security-recovery-failure',
            'nav_key' => '',
            'template' => 'case-study',
            'title' => 'Case Study: Security Exposure That Could Break Recovery | Bald Eagle Network Services',
            'description' => 'A realistic security exposure scenario showing how weak access control, backup access, and recovery planning can affect business continuity.',
            'hero_kicker' => 'Case Study #2',
            'hero_title' => 'Security Exposure Put Recovery At Risk',
            'hero_intro' => 'Network security and access control decide whether recovery stays possible after compromise.',
            'card_title' => 'Security Exposure Put Recovery At Risk',
            'card_copy' => 'A realistic exposure scenario showing how weak access control can place backup systems and recovery paths on the same destructive path as production systems.',
            'situation' => [
                'A small business relied on remote access, administrative accounts, and backup jobs that looked normal during day-to-day work.',
                'The failure risk was that production access and recovery-critical access were too closely connected. If an account or remote access path was compromised, the same path could affect backup management before recovery even began.',
                'For the owner, the business impact was not just cleanup after a security incident. It was the possibility that a compromise could interrupt operations and damage the recovery options needed to get back to work.',
            ],
            'what_was_wrong' => [
                'Excessive administrative privileges across routine user and admin paths',
                'No consistent MFA enforcement on recovery-critical access',
                'Shared credentials and weak access control boundaries',
                'Flat trust between production systems and backup administration',
                'No recovery access plan separating normal administration from incident response',
            ],
            'what_failed_eyebrow' => 'Protection Gap',
            'what_failed_title' => 'What Should Have Been Protected',
            'what_failed' => [
                'Administrative accounts, remote access, and privileged identity paths',
                'Backup management interfaces, backup deletion rights, and recovery points',
                'Network boundaries between everyday systems and recovery-critical systems',
                'Email and identity access used to reset accounts, approve changes, or recover files',
                'A recovery plan that still works when normal access cannot be trusted',
            ],
            'what_was_fixed' => [
                'Reviewed administrative access and reduced privileges to what the business actually needed',
                'Enforced MFA on recovery-critical and administrative paths',
                'Separated backup administration from general production access where possible',
                'Restricted and monitored administrative routes into backup and security-sensitive systems',
                'Documented recovery access so the business was not dependent on compromised day-to-day accounts',
            ],
            'why_it_mattered' => [
                'Backups do not protect the business if destructive access can reach them through the same control paths as production systems.',
                'Recovery depends on both data availability and control integrity. If attackers, malware, or a compromised account can damage either one, the recovery plan may fail when the owner needs it most.',
                'Network security, access control, and recovery planning have to be treated as one business continuity problem.',
            ],
            'outcome_title' => 'Security controls became part of recovery readiness.',
            'outcome' => [
                'The practical improvement was a clearer separation between everyday access, privileged administration, and recovery-critical systems.',
                'That gave the business a more realistic recovery path: fewer unnecessary privileges, stronger access control, and a plan for protecting backups before an incident turns into a continuity failure.',
            ],
            'check_cards' => [
                [
                    'title' => 'Check Administrative Access',
                    'copy' => 'Verify exactly who has privileged access to recovery-critical systems and whether each permission is truly required.',
                ],
                [
                    'title' => 'Check Backup Deletion Risk',
                    'copy' => 'Confirm compromised accounts cannot easily delete, encrypt, or disable backup data and metadata.',
                ],
                [
                    'title' => 'Check MFA Coverage',
                    'copy' => 'Ensure MFA is enforced anywhere privileged access can alter, destroy, or block recovery.',
                ],
                [
                    'title' => 'Check Backup Isolation',
                    'copy' => 'Validate backup systems are isolated from routine production compromise paths.',
                ],
            ],
            'cta' => [
                'title' => 'Start with a Recovery Assessment.',
                'copy' => 'If backup controls and privileged access have not been reviewed together, recovery risk is still unresolved.',
                'label' => 'Start a Recovery Assessment',
                'href' => recovery_assessment_href('security-recovery-risk', 'contact-form'),
            ],
            'secondary_cta' => [
                'href' => page_href('network-security'),
                'label' => 'Review Network Security',
            ],
            'related_links' => ['network-security', 'security-risk-assessments', 'services'],
        ],
        'service-area' => [
            'slug' => 'service-area',
            'path' => '/service-area',
            'nav_key' => 'service-area',
            'template' => 'service-area',
            'title' => 'Salt Lake Metro Service Area | Bald Eagle Network Services',
            'description' => 'Bald Eagle serves Salt Lake City metro businesses including West Jordan, Sandy, Draper, Murray, and South Jordan for assessment-led recovery and security work.',
            'hero_kicker' => 'Service Area',
            'hero_title' => 'Salt Lake City Service Area',
            'hero_intro' => 'Bald Eagle serves the Salt Lake metro so on-site recovery work, restore testing, and follow-through stay realistic and accountable.',
            'coverage_points' => [
                'Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Typical operating radius of roughly 30 miles',
                'Focused on local offices with 5-20 users',
                'On-site work scheduled around operational windows and business impact',
            ],
            'why_local' => [
                'Travel remains predictable for restore validation and response work',
                'Scope stays grounded in what can actually be delivered on-site',
                'Business owners have direct local accountability, not remote queue handoff',
                'Coverage claims match real operational radius',
            ],
            'local_cards' => [
                ['title' => 'Backup & Recovery', 'copy' => 'For local teams that need verified backups, monitored recovery concerns, and clearer restore expectations.', 'href' => page_href('backup-disaster-recovery')],
                ['title' => 'Monthly Verification', 'copy' => 'For businesses that need ongoing backup monitoring, restore verification, and direct follow-through on recovery drift.', 'href' => page_href('monthly-it-support-plans')],
                ['title' => 'Recovery Assessment', 'copy' => 'For owners who need to understand where ransomware and downtime risk are building before they turn into an incident.', 'href' => page_href('security-risk-assessments')],
                ['title' => 'Scoped Hardening', 'copy' => 'For access, segmentation, and recovery-critical control issues that need correction without expanding into a broad technology scope.', 'href' => page_href('network-security')],
            ],
        ],
        'services' => [
            'slug' => 'services',
            'path' => '/services',
            'nav_key' => 'services',
            'template' => 'services',
            'title' => 'Small Business IT Services in Salt Lake City | Security, Backup & Recovery | Bald Eagle',
            'description' => 'Network security, backup and disaster recovery, email and data protection, IT continuity support, and Recovery Assessments for Salt Lake small businesses.',
            'hero_kicker' => 'Service Hub',
            'hero_title' => 'Small-business IT services built around continuity, security, and recovery.',
            'hero_intro' => 'Bald Eagle helps Salt Lake small businesses protect networks, email, files, backups, and recovery paths so technology problems do not become business-wide interruptions.',
            'service_cards' => [
                [
                    'title' => 'Network Security',
                    'copy' => 'Implement, harden, and maintain small-business network security across firewalls, remote access, segmentation, account boundaries, and practical controls that reduce avoidable risk.',
                    'href' => page_href('network-security'),
                    'link_label' => 'Review Network Security',
                ],
                [
                    'title' => 'Backup & Disaster Recovery',
                    'copy' => 'Protect business files, systems, and recovery paths with backup review, restore planning, testing, and readiness checks before data loss or downtime forces the answer.',
                    'href' => page_href('backup-disaster-recovery'),
                    'link_label' => 'Review Backup & Recovery',
                ],
                [
                    'title' => 'Email & Data Protection',
                    'copy' => 'Protect and recover business email, Microsoft 365, Outlook/Exchange, OneDrive, SharePoint, and cloud files from deletion, account compromise, sync mistakes, and retention gaps.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Start With a Recovery Assessment',
                ],
                [
                    'title' => 'IT Continuity Support',
                    'copy' => 'Keep small-business systems patched, monitored, documented, supported, and recoverable so routine technology drift does not turn into downtime.',
                    'href' => page_href('monthly-it-support-plans'),
                    'link_label' => 'Review IT Continuity Support',
                ],
                [
                    'title' => 'Recovery Assessment',
                    'copy' => 'Start here to identify what is protected, what is missing, what is risky, and what can actually be recovered before a failure tests the business.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Request a Recovery Assessment',
                ],
            ],
            'proof_cards' => [
                [
                    'title' => 'Backup Existed. Recovery Failed.',
                    'copy' => 'A recovery test exposed missing data, broken restore steps, and assumptions that would have failed under pressure.',
                    'href' => page_href('case-study-backup-recovery-failure'),
                    'link_label' => 'Read Backup Recovery Case Study',
                ],
                [
                    'title' => 'Security Exposure Compromised Recovery',
                    'copy' => 'A security exposure scenario shows how weak access control can put backup systems on the same destructive path as production systems.',
                    'href' => page_href('case-study-security-recovery-failure'),
                    'link_label' => 'Read Security Recovery Case Study',
                ],
            ],
            'approach' => [
                'Use the Recovery Assessment as the front door when the risk is unclear',
                'Route network exposure and remote access issues into Network Security',
                'Route backup uncertainty, failed drives, and restore gaps into Backup & Disaster Recovery',
                'Route deleted email, cloud file mistakes, and account compromise concerns into Email & Data Protection review',
                'Route ongoing patching, monitoring, documentation, and support needs into IT Continuity Support',
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Review Backup & Recovery'],
            'faq_items' => [
                [
                    'question' => 'Can deleted business email be recovered?',
                    'answer' => 'Sometimes. Recovery depends on the mail system, retention settings, backup coverage, account state, and how long ago the message was deleted. A Recovery Assessment checks the path before assumptions become expensive.',
                ],
                [
                    'question' => 'Can OneDrive files be recovered after deletion or sync mistakes?',
                    'answer' => 'Often there are recovery options, but timing, version history, retention, backup coverage, and sync behavior matter. The review looks at OneDrive, SharePoint, and cloud file recovery as part of business data protection.',
                ],
                [
                    'question' => 'What happens if a hard drive fails?',
                    'answer' => 'The answer depends on what was stored locally, what was backed up, what can be restored, and how quickly replacement hardware or cloud access can get the user working again.',
                ],
                [
                    'question' => 'Do you help with ransomware recovery planning?',
                    'answer' => 'Yes. Planning focuses on reducing blast radius, protecting backups, defining restore order, checking account access, and knowing what the business can recover before an incident.',
                ],
                [
                    'question' => 'Why does backup testing matter?',
                    'answer' => 'Backup status alone does not prove recovery. Testing shows whether files, permissions, systems, and restore steps come back in a usable state.',
                ],
            ],
            'final_cta' => [
                'title' => 'Start with the service path that exposes the real risk.',
                'copy' => 'If you are not sure what is protected, what is missing, or what can be recovered, begin with a Recovery Assessment.',
                'href' => recovery_assessment_href('risk-assessment', 'contact-form'),
                'label' => 'Request a Recovery Assessment',
            ],
        ],
        'terms' => [
            'slug' => 'terms',
            'path' => '/terms',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Terms of Use | Bald Eagle Network Services',
            'description' => 'Terms of use for the Bald Eagle Network Services public website.',
            'hero_kicker' => 'Terms of Use',
            'hero_title' => 'Terms for use of the public website.',
            'hero_intro' => 'These terms apply to access and use of the Bald Eagle Network Services public website.',
            'sections' => [
                [
                    'title' => 'Website Purpose',
                    'paragraphs' => [
                        'This website provides general information about services offered by Bald Eagle Network Services and a means to submit business inquiries.',
                        'Nothing on the public website guarantees service availability, project acceptance, or a specific business outcome.',
                    ],
                ],
                [
                    'title' => 'Permitted Use',
                    'paragraphs' => [
                        'You may use the website to review services, learn about service area limits, and submit a legitimate business inquiry.',
                        'You may not use the website to interfere with operations, submit abusive traffic, or attempt unauthorized access to any part of the site.',
                    ],
                ],
                [
                    'title' => 'No Client Relationship',
                    'paragraphs' => [
                        'Submitting a form or contacting Bald Eagle Network Services through the website does not by itself create a client relationship, support agreement, or project commitment.',
                        'Any engagement is subject to separate written agreement and scope approval.',
                    ],
                ],
                [
                    'title' => 'Changes',
                    'paragraphs' => [
                        'Website content and these terms may be updated from time to time without prior notice.',
                    ],
                ],
            ],
        ],
    ];

    return $definitions;
}
