<?php
declare(strict_types=1);

function site_page_definitions(): array
{
    static $definitions;

    if ($definitions !== null) {
        return $definitions;
    }

    $definitions = [
        '404' => [
            'slug' => '404',
            'path' => '/404.php',
            'nav_key' => '',
            'template' => '404',
            'title' => 'Page Not Found | Bald Eagle Network Services',
            'description' => 'The page you requested was not found.',
            'hero_kicker' => '404',
            'hero_title' => 'That page does not exist or is no longer available.',
            'hero_intro' => 'Return to the main site, review services, or send a request if you were looking for support, project help, or a security review.',
            'robots' => 'noindex,follow',
        ],
        'about' => [
            'slug' => 'about',
            'path' => '/about',
            'nav_key' => 'about',
            'template' => 'about',
            'title' => 'About Bald Eagle Network Services | Local Recovery Accountability',
            'description' => 'Bald Eagle helps Salt Lake metro businesses prove recoverability, fix failures, and keep scope accountable.',
            'hero_kicker' => 'About Bald Eagle',
            'hero_title' => 'About Bald Eagle Network Services',
            'hero_intro' => 'Bald Eagle is built for local businesses that need direct communication, firm scope boundaries, and recovery outcomes that hold up when operations are under pressure.',
            'paragraphs' => [
                'The operating model is explicit: verify what can be restored, reduce downtime exposure, and correct the control gaps that increase ransomware blast radius.',
                'Work is scoped in writing, executed in defined phases, and closed with documented findings and next actions.',
                'Bald Eagle serves small offices in the Salt Lake metro, especially dental, legal, construction, and professional service firms with 5-20 users.',
            ],
            'principles' => [
                'Start with recoverability, not tool sprawl',
                'Keep scope defined and decisions traceable',
                'Run restore testing instead of assuming backups are enough',
                'Stay local so accountability stays real',
            ],
            'fit_cards' => [
                [
                    'title' => 'Best Fit',
                    'copy' => 'Salt Lake metro businesses with 5-20 users that rely on file and account access to stay open.',
                ],
                [
                    'title' => 'How We Operate',
                    'copy' => 'Assessment first, remediation second, monitoring only when justified by business risk and defined scope.',
                ],
                [
                    'title' => 'What To Expect',
                    'copy' => 'Direct answers, prioritized findings, and execution focused on recovery confidence and operational stability.',
                ],
            ],
            'final_cta' => [
                'title' => 'Start with a risk assessment, not a generic IT pitch.',
                'copy' => 'If downtime, ransomware resilience, or backup confidence is unclear, begin with a scoped assessment and get an actionable recovery path.',
                'href' => page_href('contact') . '?service=risk-assessment',
                'label' => 'Request a Risk Assessment',
            ],
        ],
        'backup-disaster-recovery' => [
            'slug' => 'backup-disaster-recovery',
            'path' => '/backup-disaster-recovery',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Backup & Recovery Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Backup and recovery services in Salt Lake City for businesses that need verified restores and practical continuity planning.',
            'hero_kicker' => 'Backup & Disaster Recovery',
            'hero_title' => 'Backup, Recovery, and Restore Confidence',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses monitor backups, verify restores, and shorten recovery time when ransomware, deletion, or system failure hits.',
            'card_title' => 'Backup & Disaster Recovery',
            'card_copy' => 'Backup monitoring, restore testing, retention review, and recovery planning tied to business continuity.',
            'pain_points' => [
                'Backups appear healthy but no one knows whether key data can actually be restored',
                'Retention settings do not reflect operational downtime or legal needs',
                'Critical systems have no documented order of recovery after an incident',
                'Ransomware planning stops at backup status instead of restore readiness',
            ],
            'included' => [
                'Backup configuration and monitoring review',
                'Recovery priorities aligned to business operations',
                'Restore testing guidance or supervised execution',
                'Continuity recommendations tied to actual systems and dependencies',
            ],
            'who_for_title' => 'For offices that cannot absorb data loss or long downtime.',
            'who_for_copy' => 'This service fits small professional-service businesses and local offices that rely on file access, account access, line-of-business systems, or shared data to stay open.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'When recovery planning is vague, incident response becomes guesswork. That extends downtime and turns manageable failures into business-wide disruption.',
                'Verified restores create a more honest continuity plan because owners can see what recovery would actually require before a real incident forces the answer.',
            ],
            'deliverables' => [
                'Backup and recovery posture review',
                'Prioritized restore and continuity concerns',
                'Retention, monitoring, and restoration recommendations',
                'Defined next steps for remediation or ongoing continuity oversight',
            ],
            'cta_title' => 'Need to know whether your backups will hold up under ransomware or outage pressure?',
            'cta_copy' => 'Start with the system, file set, or business process you cannot afford to lose for even a day.',
            'contact_service_type' => 'backup-dr',
            'primary_cta_label' => 'Check Backup Readiness',
            'process_heading' => 'How backup verification turns into a real recovery plan.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Review', 'copy' => 'Identify the backups, systems, and restore assumptions tied to your highest downtime risk.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Confirm what can be restored, what is untested, and where ransomware pressure would break the plan.'],
                ['step' => '03', 'title' => 'Prioritize', 'copy' => 'Deliver the next actions for restore testing, retention fixes, and continuity improvements.'],
            ],
            'secondary_cta' => ['href' => page_href('managed-it-services'), 'label' => 'See Recovery Planning'],
            'related_links' => ['managed-it-services', 'security-risk-assessments', 'monthly-it-support-plans'],
        ],
        'compliance-readiness' => [
            'slug' => 'compliance-readiness',
            'path' => '/compliance-readiness',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Compliance Readiness Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Continuity and control readiness services in Salt Lake City for small businesses preparing for audits, insurance reviews, or client pressure.',
            'hero_kicker' => 'Compliance Readiness',
            'hero_title' => 'Compliance Readiness Support',
            'hero_intro' => 'Bald Eagle helps Salt Lake City businesses prepare for audits and client reviews by tightening controls, documentation, access standards, and device discipline.',
            'card_title' => 'Compliance Readiness',
            'card_copy' => 'Control cleanup and remediation support ahead of audits, questionnaires, and client reviews.',
            'pain_points' => [
                'Client or insurance questionnaires exposing weak answers',
                'No documented control owner for key security areas',
                'Account access and endpoint settings that are inconsistent',
                'Too much scrambling right before a review or renewal',
            ],
            'included' => [
                'Gap review against stated readiness needs',
                'Control cleanup recommendations and remediation support',
                'Documentation assistance for current-state explanations',
                'Alignment between support work, security work, and audit pressure',
            ],
            'who_for_title' => 'For businesses preparing for outside scrutiny.',
            'who_for_copy' => 'This service fits organizations that are facing a client security review, insurance requirement, compliance checklist, or internal pressure to clean up control issues before they become expensive.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Compliance pressure often reveals operational weaknesses that already exist. Waiting until the deadline usually makes remediation more expensive and more disruptive.',
                'Readiness work gives owners a more controlled way to fix the basics, document the environment, and stop guessing about what is actually missing.',
            ],
            'deliverables' => [
                'Readiness gap summary',
                'Control remediation priorities',
                'Implementation support recommendations',
                'Defined path into project work or monthly support if needed',
            ],
            'cta_title' => 'Need to clean up controls before the next review?',
            'cta_copy' => 'Start with the questionnaire, audit pressure, or control area that is currently weakest.',
            'contact_service_type' => 'compliance',
            'primary_cta_label' => 'Get a Business Continuity Review',
            'process_heading' => 'How readiness work moves from outside pressure to practical fixes.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Identify', 'copy' => 'Review the questionnaire, insurance demand, or audit pressure revealing the current gap.'],
                ['step' => '02', 'title' => 'Map', 'copy' => 'Tie the control weakness to recovery, access, or continuity risk inside the real environment.'],
                ['step' => '03', 'title' => 'Close', 'copy' => 'Return a prioritized remediation path with the documentation or cleanup steps that matter first.'],
            ],
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Request a Risk Assessment'],
            'related_links' => ['security-risk-assessments', 'microsoft-365-services', 'endpoint-management'],
        ],
        'contact' => [
            'slug' => 'contact',
            'path' => '/contact',
            'nav_key' => 'contact',
            'template' => 'contact',
            'title' => 'Request a Cybersecurity Risk Assessment | Salt Lake Metro | Bald Eagle',
            'description' => 'Request a cybersecurity risk assessment for your Salt Lake metro business and find backup, recovery, and ransomware weaknesses before downtime does.',
            'hero_kicker' => 'Risk Assessment Request',
            'hero_title' => 'Request a Risk Assessment',
            'hero_intro' => 'Use this short form to start a recovery-focused cybersecurity assessment for backup readiness, ransomware resilience, account access risk, and business continuity planning.',
            'contact_points' => [
                'Name the system, data set, or workflow your team cannot lose',
                'Tell us when you last completed a successful restore test',
                'Flag whether ransomware, downtime, or account access is the bigger concern',
                'Share any looming deadline such as insurance, audit, or client pressure',
                'Keep it short if needed; the goal is to identify the next review step quickly',
            ],
            'response_points' => [
                'Direct response with defined scope and next action',
                'Requests filtered to Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Recommendation for assessment findings, backup verification, recovery planning, or continuity monitoring',
                'No ticket maze and no generic MSP sales sequence',
            ],
            'form_title' => 'Start the Assessment',
            'form_copy' => 'Assessment value: $500, waived for qualified local businesses. Backups are not recovery unless restore testing proves it.',
        ],
        'cybersecurity-salt-lake-city' => [
            'slug' => 'cybersecurity-salt-lake-city',
            'path' => '/cybersecurity-salt-lake-city',
            'nav_key' => 'services',
            'template' => 'local',
            'robots' => 'noindex,follow',
            'title' => 'Cybersecurity Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Ransomware resilience and control hardening in Salt Lake City for small businesses that need practical risk reduction.',
            'hero_kicker' => 'Salt Lake City Cybersecurity',
            'hero_title' => 'Cybersecurity Services in Salt Lake City',
            'hero_intro' => 'Bald Eagle helps Salt Lake City small businesses reduce risk through recovery testing, hardening, backup review, and practical remediation.',
            'card_title' => 'Cybersecurity Salt Lake City',
            'card_copy' => 'Local cybersecurity assessments and remediation for Salt Lake City businesses.',
            'pain_points' => [
                'Security concerns with no practical triage path',
                'Remote access, identity, or backup concerns building over time',
                'Outside pressure from clients, insurers, or leadership',
                'No clear understanding of what needs to be fixed first',
            ],
            'included' => [
                'Risk assessments for local business environments',
                'Network and control remediation guidance',
                'Account access and endpoint issues included where relevant',
                'Practical recommendations aligned to business operations',
            ],
            'who_for_title' => 'For Salt Lake City companies that want clarity on security priorities.',
            'who_for_copy' => 'This page is for owners and managers who know the environment needs stronger controls but do not need generic fear language or enterprise theater.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Security problems tend to be cumulative. Weak identity, unverified backups, broad permissions, and old firewall changes create risk that is hard to see until something goes wrong.',
                'A local review gives the business a clearer path to remediation and a tighter connection between on-site reality and control recommendations.',
            ],
            'deliverables' => [
                'Salt Lake City security review and findings',
                'Prioritized corrective actions',
                'Next-step recommendation for project work or ongoing support',
                'Internal links to related services and assessment pages',
            ],
            'cta_title' => 'Need a cybersecurity review for a Salt Lake City business?',
            'cta_copy' => 'Describe the control concern, business pressure, or recent security issue driving the request.',
            'contact_service_type' => 'risk-assessment',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['security-risk-assessments', 'network-security', 'it-services-salt-lake-city'],
        ],
        'endpoint-management' => [
            'slug' => 'endpoint-management',
            'path' => '/endpoint-management',
            'nav_key' => 'services',
            'template' => 'service',
            'robots' => 'noindex,follow',
            'title' => 'Endpoint Management Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Endpoint management services in Salt Lake City for small businesses that need stronger device standards, patching discipline, and user workstation control.',
            'hero_kicker' => 'Endpoint Management',
            'hero_title' => 'Endpoint Management for Small Businesses',
            'hero_intro' => 'Bald Eagle helps Salt Lake City businesses standardize devices, improve patching, and reduce recurring support friction tied to weak endpoint control.',
            'card_title' => 'Endpoint Management',
            'card_copy' => 'Device standards, patching discipline, and workstation control for small business teams.',
            'pain_points' => [
                'Workstations configured differently across the company',
                'Weak patch hygiene or no real endpoint owner',
                'Stale devices, uncertain inventory, and poor offboarding',
                'User issues that keep repeating because the endpoint baseline is weak',
            ],
            'included' => [
                'Endpoint review and standards assessment',
                'Patch and device management recommendations',
                'Inventory and lifecycle guidance',
                'Support alignment between devices, account access controls, and security controls',
            ],
            'who_for_title' => 'For businesses whose device baseline is inconsistent.',
            'who_for_copy' => 'This service fits companies that need better visibility and control over user workstations, laptops, and day-to-day device administration.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Weak endpoint discipline creates more tickets, more risk, and more wasted time during onboarding, offboarding, and support.',
                'A stronger endpoint baseline improves security, reduces recurring friction, and makes support faster because the environment is less chaotic.',
            ],
            'deliverables' => [
                'Endpoint posture summary',
                'Standardization and patching recommendations',
                'Prioritized remediation list',
                'Next-step path into managed support if appropriate',
            ],
            'cta_title' => 'Need better control over company devices?',
            'cta_copy' => 'Start with the endpoint issue, patching concern, or user device pattern that keeps resurfacing.',
            'contact_service_type' => 'endpoint-management',
            'secondary_cta' => ['href' => page_href('managed-it-services'), 'label' => 'See Recovery Assurance'],
            'related_links' => ['managed-it-services', 'microsoft-365-services', 'monthly-it-support-plans'],
        ],
        'faq' => [
            'slug' => 'faq',
            'path' => '/faq',
            'nav_key' => '',
            'template' => 'faq',
            'title' => 'Recovery Readiness Test FAQ | Bald Eagle Network Services',
            'description' => 'Answers about Recovery Readiness Testing, backup recovery risk, restore testing, and Salt Lake metro service fit.',
            'hero_kicker' => 'Frequently Asked Questions',
            'hero_title' => 'Recovery Readiness Test FAQ',
            'hero_intro' => 'These answers cover fit, test scope, backup validation, restore testing, and local coverage in the Salt Lake metro.',
            'faq_items' => [
                ['question' => 'What size company is the best fit?', 'answer' => 'The public site is written for small professional-service businesses and local offices with roughly 5 to 20 employees that depend on continuity but do not have deep internal IT coverage.'],
                ['question' => 'Do you only support businesses in Salt Lake?', 'answer' => 'Yes. Service is limited to the Salt Lake metro and nearby businesses within about a 30-mile radius.'],
                ['question' => 'Can we start with a test instead of ongoing service?', 'answer' => 'Yes. Most engagements begin with a Recovery Readiness Test to establish facts before discussing remediation or monitoring.'],
                ['question' => 'Do you provide full MSP helpdesk coverage?', 'answer' => 'No. The site is intentionally focused on backup and recovery outcomes, recovery testing, continuity planning, and scoped security work that protects those outcomes.'],
                ['question' => 'What does continuity monitoring cover?', 'answer' => 'Continuity monitoring is limited oversight tied to backup health, recovery readiness, retention concerns, and follow-through on issues that would materially affect downtime or restore success.'],
                ['question' => 'Do you handle account access and endpoint issues?', 'answer' => 'Yes, but only where those systems affect recovery speed, identity protection, file access, or business continuity. The goal is not broad platform administration for its own sake.'],
                ['question' => 'Can you help with security hardening?', 'answer' => 'Yes, in a scoped way. Hardening work is aimed at reducing blast radius, tightening access, and protecting recovery paths rather than turning the engagement into a broad network security program.'],
                ['question' => 'What happens after we submit the form?', 'answer' => 'The request is reviewed for fit, urgency, and service area. You get a direct response with the best next step and scope for the assessment.'],
            ],
            'final_cta' => [
                'title' => 'Need answers tied to your own environment?',
                'copy' => 'The fastest way to stop guessing is to request an assessment and get a recovery-focused next step for your business.',
                'href' => page_href('contact') . '?service=risk-assessment',
                'label' => 'Request a Risk Assessment',
            ],
        ],
        'home' => [
            'slug' => 'home',
            'path' => '/',
            'nav_key' => 'services',
            'template' => 'home',
            'title' => 'Small Business Cybersecurity Risk Assessments in Salt Lake City | Bald Eagle',
            'description' => 'Request a small-business cybersecurity risk assessment in the Salt Lake metro. Verify backup readiness, ransomware resilience, and recovery planning before downtime hits.',
            'hero_kicker' => 'Salt Lake Recovery Readiness',
            'hero_title' => 'If your systems went down today, how long would it take to recover?',
            'hero_intro' => 'Backups are not recovery. Bald Eagle runs Recovery Readiness Tests for Salt Lake metro businesses so owners can verify restore reality before ransomware or failure forces the answer.',
            'hero_panel_label' => 'Questions To Answer Now',
            'trust_points' => [
                'When was your last successful restore test?',
                'Could your business recover from ransomware today?',
                'What happens if your main system is unavailable tomorrow?',
                'Are your backups verified or only reporting green?',
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Check Backup Readiness'],
            'trust_strip' => [
                'Risk assessment first',
                'Verified recovery testing',
                'Salt Lake metro only',
                'Backup restore validation',
                'Reduced downtime',
            ],
            'core_services' => [
                [
                    'title' => 'Dental Offices',
                    'copy' => 'Chart systems, imaging access, and scheduling continuity checked against restore order and tested recovery reality.',
                    'href' => page_href('backup-disaster-recovery'),
                    'link_label' => 'Check Backup Readiness',
                ],
                [
                    'title' => 'Legal Offices',
                    'copy' => 'Matter files, account access controls, and ransomware recovery dependencies checked before a disruption.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Request a Risk Assessment',
                ],
                [
                    'title' => 'Construction Firms',
                    'copy' => 'Field-to-office file flow, remote access controls, and backup restore testing aligned to active project risk.',
                    'href' => page_href('security-risk-assessments'),
                    'link_label' => 'Schedule a Recovery Review',
                ],
                [
                    'title' => 'Professional Service Offices',
                    'copy' => 'Owner-led teams get clear findings, scoped remediation, and continuity monitoring where it is justified.',
                    'href' => page_href('network-security'),
                    'link_label' => 'Review Ransomware Resilience',
                ],
            ],
            'warning_signs' => [
                [
                    'title' => 'When was your last successful restore test?',
                    'copy' => 'Teams discover restore failures only during a real incident because test restores were never run against critical workloads.',
                ],
                [
                    'title' => 'Could your business recover from ransomware today?',
                    'copy' => 'Former staff access, broad permission groups, and weak MFA create avoidable exposure and slow recovery after account compromise.',
                ],
                [
                    'title' => 'What gets restored first if the main system fails?',
                    'copy' => 'Owners know systems are important but cannot name what gets restored first or what dependencies block operations.',
                ],
                [
                    'title' => 'Are you relying on backups without a continuity plan?',
                    'copy' => 'Without recovery sequencing and control hardening, backups alone do not prevent extended downtime.',
                ],
            ],
            'why_cards' => [
                [
                    'title' => 'Assessment first',
                    'copy' => 'Every engagement starts with a defined Recovery Readiness Test to establish real risk, not assumptions.',
                ],
                [
                    'title' => 'Scope stays controlled',
                    'copy' => 'Recommendations are prioritized by operational impact and recovery risk, not by broad technology wish lists.',
                ],
                [
                    'title' => 'Accountability stays local',
                    'copy' => 'Coverage remains inside the Salt Lake metro so on-site recovery, remediation, and follow-through remain practical.',
                ],
            ],
            'proof_strip' => [
                [
                    'title' => 'Recover faster from incidents',
                    'copy' => 'Know what must be restored first, what recovery dependencies exist, and where the real downtime risk lives.',
                ],
                [
                    'title' => 'Prove backups before failure',
                    'copy' => 'A green dashboard does not mean your business can recover. Restore testing does.',
                ],
                [
                    'title' => 'Contain ransomware downtime',
                    'copy' => 'Tighten account access and recovery dependencies so an attack does not turn into a prolonged shutdown.',
                ],
            ],
            'engagements' => [
                [
                    'title' => 'If You Are Stable',
                    'copy' => 'Monthly continuity monitoring keeps backup validation and recovery risk from drifting back into assumptions.',
                    'points' => [
                        'Backup and restore monitoring follow-through',
                        'Recovery issue tracking and prioritization',
                        'Escalation when continuity risk increases',
                    ],
                    'href' => page_href('monthly-it-support-plans'),
                    'link_label' => 'See Monthly Continuity',
                ],
                [
                    'title' => 'If You Fail The Test',
                    'copy' => 'Run a remediation project with defined scope and fixed outcomes to close critical recovery and control failures.',
                    'points' => [
                        'Defined scope and recovery objective',
                        'Clear deliverables',
                        'Focused technical execution',
                    ],
                    'href' => page_href('one-off-it-projects'),
                    'link_label' => 'See Remediation Projects',
                ],
            ],
            'access_control' => [
                'title' => 'Account access controls are part of recovery, not a side task.',
                'copy' => 'Identity, email and file access, and admin boundaries directly affect recovery speed after ransomware, account compromise, or data loss.',
                'points' => [
                    'Identity, MFA, and access policy review',
                    'Email and file access dependency checks',
                    'Administrative boundary cleanup tied to restore readiness',
                    'Scoped hardening around business-critical workflows',
                ],
            ],
            'service_area' => [
                'title' => 'Local coverage limited to the Salt Lake metro.',
                'copy' => 'Bald Eagle works within a 30-mile radius of Salt Lake City so continuity planning, on-site recovery work, and follow-through stay realistic.',
                'points' => [
                    'Salt Lake City and nearby commercial corridors',
                    'Reasonable travel windows for on-site recovery work',
                    'No oversized multi-market footprint',
                    'Local businesses only',
                ],
            ],
            'process' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Review business impact, recovery dependencies, and the controls most likely to fail under pressure.'],
                ['step' => '02', 'title' => 'Verify', 'copy' => 'Test what can be restored, what fails silently, and what assumptions are currently unsafe.'],
                ['step' => '03', 'title' => 'Harden', 'copy' => 'Tighten the access and control gaps that would make a recovery event worse.'],
                ['step' => '04', 'title' => 'Recover', 'copy' => 'Document next steps so the business can respond faster when an incident actually happens.'],
            ],
            'faq_items' => [
                [
                    'question' => 'Do you only work with companies in Salt Lake?',
                    'answer' => 'Yes. The public site is intentionally limited to the Salt Lake metro and nearby businesses within roughly 30 miles.',
                ],
                [
                    'question' => 'Can we start with a single project?',
                    'answer' => 'Yes, but the first step is still an assessment so project scope is tied to risk and recoverability.',
                ],
                [
                    'question' => 'Do you support account access and identity cleanup?',
                    'answer' => 'Yes, where account access affects recovery speed, identity risk, file access, or business continuity. The focus is continuity, not broad platform administration for its own sake.',
                ],
                [
                    'question' => 'What kinds of businesses are the best fit?',
                    'answer' => 'Small professional-service businesses and local offices with roughly 5 to 20 employees that rely on continuity and need clearer recovery outcomes.',
                ],
            ],
            'final_cta' => [
                'title' => 'Request a Risk Assessment',
                'copy' => 'Assessment value: $500, waived for qualified local businesses. If you have never restored it, you have not proven it.',
            ],
        ],
        'it-services-salt-lake-city' => [
            'slug' => 'it-services-salt-lake-city',
            'path' => '/it-services-salt-lake-city',
            'nav_key' => 'services',
            'template' => 'local',
            'robots' => 'noindex,follow',
            'title' => 'IT Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Recovery-focused IT services in Salt Lake City for small businesses that need dependable support and local execution.',
            'hero_kicker' => 'Salt Lake City IT Services',
            'hero_title' => 'Local IT Services in Salt Lake City',
            'hero_intro' => 'Bald Eagle supports Salt Lake City small businesses that need dependable IT help, recovery discipline, infrastructure cleanup, and direct local accountability.',
            'card_title' => 'IT Services Salt Lake City',
            'card_copy' => 'Local IT support and project work for businesses in Salt Lake City.',
            'pain_points' => [
                'No clear IT owner inside a growing local business',
                'Too much time lost to recurring support issues',
                'Cloud and office systems drifting without oversight',
                'Need for local project execution instead of remote-only advice',
            ],
            'included' => [
                'Monthly support and project work for Salt Lake City offices',
                'Account access and user support tied to recovery outcomes',
                'Endpoint, network, and backup remediation as needed',
                'Local coverage that stays inside a practical radius',
            ],
            'who_for_title' => 'For Salt Lake City businesses that want direct local support.',
            'who_for_copy' => 'This page is aimed at companies operating in Salt Lake City that need a small-business IT partner with a tighter service area and clearer support boundaries than broad regional providers.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Local support matters when offices need on-site remediation, network work, or a real understanding of the business environment instead of purely remote assumptions.',
                'A tighter radius also helps keep response expectations realistic and avoids overselling geography.',
            ],
            'deliverables' => [
                'Local Salt Lake City service review',
                'Support or project fit recommendation',
                'Defined next step for monthly support or scoped remediation',
                'Internal links to service-specific pages',
            ],
            'cta_title' => 'Need local IT support inside Salt Lake City?',
            'cta_copy' => 'Describe the issue, the office setup, and whether you need monthly support or a focused project.',
            'contact_service_type' => 'managed-it',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['managed-it-support-salt-lake-city', 'microsoft-365-support-salt-lake-city', 'cybersecurity-salt-lake-city'],
        ],
        'managed-it-services' => [
            'slug' => 'managed-it-services',
            'path' => '/managed-it-services',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Recovery Assurance Services in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Recovery Assurance services for Salt Lake metro businesses that need defined restore sequencing, dependency mapping, and verified recovery confidence.',
            'hero_kicker' => 'Recovery Assurance',
            'hero_title' => 'Recovery Assurance for Small Businesses',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses define what must be restored first, what dependencies are still risky, and what continuity gaps need attention before an incident forces the answer.',
            'card_title' => 'Recovery Assurance',
            'card_copy' => 'Continuity prioritization, dependency review, and recovery planning for small business environments.',
            'pain_points' => [
                'Critical systems have no clear order of recovery',
                'Backups exist but no one has mapped the real business dependencies',
                'Owners are unsure how long the business could operate during an outage',
                'Response plans rely on tribal knowledge instead of tested recovery steps',
            ],
            'included' => [
                'Business continuity and dependency review',
                'Recovery sequencing for critical systems and workflows',
                'Identification of restore blockers and recovery assumptions',
                'Recommendations for follow-up verification or scoped hardening',
            ],
            'who_for_title' => 'Built for owner-led teams without internal continuity depth.',
            'who_for_copy' => 'This service fits small professional-service businesses and offices that cannot afford guesswork during an outage and need a more credible continuity posture.',
            'why_title' => 'Why recovery readiness matters',
            'why_paragraphs' => [
                'When recovery decisions are improvised, downtime stretches and owners find out too late which assumptions were wrong.',
                'A readiness review creates a more realistic path to continuity because it connects business priorities, systems, and restore expectations before an incident occurs.',
            ],
            'deliverables' => [
                'Recovery readiness summary',
                'Priority sequence for critical systems and workflows',
                'List of restore blockers or continuity gaps',
                'Clear next-step plan for testing, hardening, or ongoing monitoring',
            ],
            'cta_title' => 'Need a clearer recovery plan before the next outage or ransomware event?',
            'cta_copy' => 'Start with the system, workflow, or unanswered recovery question that would hurt the business most if it failed.',
            'contact_service_type' => 'managed-it',
            'primary_cta_label' => 'Schedule a Recovery Planning Call',
            'process_heading' => 'How a recovery planning engagement is structured.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Scope', 'copy' => 'Define the systems, workflows, and downtime assumptions that deserve immediate attention.'],
                ['step' => '02', 'title' => 'Sequence', 'copy' => 'Map the restore order, dependencies, and blockers that would slow a real recovery.'],
                ['step' => '03', 'title' => 'Document', 'copy' => 'Turn the findings into a practical recovery plan with clear next actions.'],
            ],
            'secondary_cta' => ['href' => page_href('monthly-it-support-plans'), 'label' => 'See Stability & Monitoring'],
            'related_links' => ['backup-disaster-recovery', 'monthly-it-support-plans', 'security-risk-assessments'],
        ],
        'managed-it-support-salt-lake-city' => [
            'slug' => 'managed-it-support-salt-lake-city',
            'path' => '/managed-it-support-salt-lake-city',
            'nav_key' => 'plans',
            'template' => 'local',
            'robots' => 'noindex,follow',
            'title' => 'Managed IT Support in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Continuity monitoring in Salt Lake City for small businesses that need monthly recovery oversight and local accountability.',
            'hero_kicker' => 'Salt Lake City Continuity Monitoring',
            'hero_title' => 'Continuity Monitoring in Salt Lake City',
            'hero_intro' => 'This local page is for Salt Lake City businesses that need monthly recovery oversight, stronger standards, and a nearby operating partner.',
            'card_title' => 'Managed IT Support Salt Lake City',
            'card_copy' => 'Monthly support coverage for Salt Lake City businesses needing steadier IT ownership.',
            'pain_points' => [
                'Unclear ownership of daily support and environment hygiene',
                'Recurring user issues interrupting small teams',
                'Devices and account access controls drifting over time',
                'Need for a local partner with realistic on-site coverage',
            ],
            'included' => [
                'Monthly support structure for local businesses',
                'User support, device oversight, and account-access administration',
                'Security-minded recommendations as part of routine service',
                'Escalation into project work when bigger changes are needed',
            ],
            'who_for_title' => 'For Salt Lake City businesses past the ad hoc stage.',
            'who_for_copy' => 'This page is for companies that have outgrown informal tech support and need a more structured monthly relationship without hiring full internal IT staff.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Managed support creates consistency across support requests, device management, access control, and small ongoing improvements.',
                'That consistency is usually the difference between a business that is constantly reacting and one that can plan around its technology.',
            ],
            'deliverables' => [
                'Managed support fit review for Salt Lake City operations',
                'Defined monthly coverage recommendation',
                'Initial priority list for stability and security work',
                'Direct path into engagement planning',
            ],
            'cta_title' => 'Need continuity monitoring in Salt Lake City without bloated MSP packaging?',
            'cta_copy' => 'Send the current headcount, office location, and the support pattern that is creating the most drag.',
            'contact_service_type' => 'managed-it',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['monthly-it-support-plans', 'managed-it-services', 'it-services-salt-lake-city'],
        ],
        'microsoft-365-services' => [
            'slug' => 'microsoft-365-services',
            'path' => '/microsoft-365-services',
            'nav_key' => 'services',
            'template' => 'service',
            'robots' => 'noindex,follow',
            'title' => 'Identity & Access Recovery Controls in Salt Lake City | Bald Eagle',
            'description' => 'Identity and access control services in Salt Lake City for small businesses that need account recovery discipline tied to continuity outcomes.',
            'hero_kicker' => 'Identity & Access Review',
            'hero_title' => 'Identity and Access Controls for Recovery-Critical Workflows',
            'hero_intro' => 'Bald Eagle helps Salt Lake City small businesses control account access, identity, permissions, and day-to-day admin drift that slows recovery.',
            'card_title' => 'Identity & Access Review',
            'card_copy' => 'Account administration, identity controls, access discipline, and user support tied to continuity.',
            'pain_points' => [
                'Users, groups, and licenses that no longer reflect reality',
                'Weak MFA or identity settings around sensitive access',
                'Mailbox, SharePoint, and Teams permissions with too much spread',
                'No one clearly responsible for access hygiene',
            ],
            'included' => [
                'Account administration and access support',
                'Identity, MFA, and access policy review',
                'Email and file access operational support',
                'Corrective security and cleanup work tied to business use',
            ],
            'who_for_title' => 'For companies depending on account access every day.',
            'who_for_copy' => 'This service fits businesses where email, collaboration, identity, and file access all run through cloud accounts and weak administration is starting to show up as risk or inefficiency.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Poor account administration creates more than user frustration. It creates over-permissioned access, weak offboarding, and uneven protection around business-critical data.',
                'A clean access environment is easier to support, easier to secure, and easier to explain when an owner needs to understand risk.',
            ],
            'deliverables' => [
                'Identity and access support and cleanup plan',
                'Administrative corrections or recommendations',
                'Identity and access review outcomes',
                'Defined next steps for deeper security or compliance work',
            ],
            'cta_title' => 'Need identity and access support that goes beyond password resets?',
            'cta_copy' => 'Start with the account-access issue or cleanup project that needs a clear owner.',
            'contact_service_type' => 'microsoft-365',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['managed-it-services', 'compliance-readiness', 'microsoft-365-support-salt-lake-city'],
        ],
        'microsoft-365-support-salt-lake-city' => [
            'slug' => 'microsoft-365-support-salt-lake-city',
            'path' => '/microsoft-365-support-salt-lake-city',
            'nav_key' => 'services',
            'template' => 'local',
            'robots' => 'noindex,follow',
            'title' => 'Account Access Support in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Account access support in Salt Lake City for small businesses that need identity controls and practical administration.',
            'hero_kicker' => 'Salt Lake City Account Access Support',
            'hero_title' => 'Account Access Support in Salt Lake City',
            'hero_intro' => 'This local page is for Salt Lake City businesses that need access cleanup, identity control, and practical account administration.',
            'card_title' => 'Account Access Support Salt Lake City',
            'card_copy' => 'Local account-access support for identity, permissions, and administration cleanup.',
            'pain_points' => [
                'Access sprawl caused by years of unchecked changes',
                'Licensing and user access not matching current staff',
                'Email and file-access settings with weak ownership',
                'Need for local support tied to business operations',
            ],
            'included' => [
                'Access administration and cleanup guidance',
                'Identity and MFA control review',
                'User support and account access issue resolution',
                'Recommendations linked to broader managed support if needed',
            ],
            'who_for_title' => 'For Salt Lake City companies leaning heavily on cloud account access.',
            'who_for_copy' => 'This page is meant for businesses where cloud identity and file access run daily operations and the access model now needs deliberate administration.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Small access mistakes compound over time. Weak offboarding, stale accounts, broad permissions, and inconsistent MFA all add operational and security risk.',
                'A cleaner access model is easier for users, easier to manage, and easier to defend when outside requirements increase.',
            ],
            'deliverables' => [
                'Salt Lake City account-access support review',
                'Access cleanup and control recommendations',
                'Defined support path for administration or remediation',
                'Internal links to related security and support services',
            ],
            'cta_title' => 'Need Salt Lake City account-access support with tighter control?',
            'cta_copy' => 'Send the access issue, current headcount, and the area causing the most friction.',
            'contact_service_type' => 'microsoft-365',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['microsoft-365-services', 'managed-it-services', 'compliance-readiness'],
        ],
        'monthly-it-support-plans' => [
            'slug' => 'monthly-it-support-plans',
            'path' => '/monthly-it-support-plans',
            'nav_key' => 'plans',
            'template' => 'commercial',
            'title' => 'Continuity Monitoring Plans in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Continuity monitoring plans for Salt Lake businesses that need ongoing oversight of backup health, recovery gaps, and business continuity follow-through.',
            'hero_kicker' => 'Continuity Monitoring',
            'hero_title' => 'Continuity Monitoring Plans',
            'hero_intro' => 'These plans fit Salt Lake businesses that want ongoing oversight of backup readiness, restore concerns, and continuity issues without turning the engagement into a broad MSP contract.',
            'card_title' => 'Continuity Monitoring',
            'card_copy' => 'Monthly continuity oversight for backup health, recovery blockers, and restore readiness.',
            'pain_points' => [
                'Backup issues drift because no one is following them through month to month',
                'Restore concerns surface only during audits, renewals, or incidents',
                'Continuity tasks keep getting postponed behind daily operations',
                'Leadership wants ongoing visibility without buying a generic helpdesk contract',
            ],
            'included' => [
                'Ongoing review of continuity priorities and follow-through items',
                'Backup health and restore readiness oversight',
                'Scoped recommendations when recovery risk increases',
                'Escalation path for testing, remediation, or hardening work',
            ],
            'who_for_title' => 'For companies that know recovery cannot stay ad hoc.',
            'who_for_copy' => 'These plans fit businesses that want continuity issues watched consistently but do not want broad endpoint management, generic helpdesk promises, or an all-purpose MSP agreement.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Continuity issues tend to drift when no one owns them. Monitoring keeps backup, restore, and recovery work from slipping back into assumptions.',
                'It also gives the business a steadier path for follow-through after assessments or restore testing expose gaps that should not be ignored.',
            ],
            'deliverables' => [
                'Defined continuity monitoring scope',
                'Structured monthly review cadence',
                'Priority guidance for ongoing continuity improvements',
                'Clear boundary between monitoring and separate remediation work',
            ],
            'cta_title' => 'Need continuity oversight without signing up for a broad MSP relationship?',
            'cta_copy' => 'Use the review form to outline what needs to be watched, what keeps slipping, and what recovery risk worries you most.',
            'contact_service_type' => 'managed-it',
            'primary_cta_label' => 'Get a Business Continuity Review',
            'process_heading' => 'How continuity monitoring stays lean and recovery-focused.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Baseline', 'copy' => 'Start from the current assessment findings, open restore concerns, and known continuity risks.'],
                ['step' => '02', 'title' => 'Monitor', 'copy' => 'Track backup health, testing follow-through, and recovery blockers before they drift back into guesswork.'],
                ['step' => '03', 'title' => 'Escalate', 'copy' => 'Raise the right project or hardening work only when the business risk justifies it.'],
            ],
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Request a Risk Assessment'],
            'related_links' => ['managed-it-services', 'backup-disaster-recovery', 'security-risk-assessments'],
        ],
        'network-cabling-wifi' => [
            'slug' => 'network-cabling-wifi',
            'path' => '/network-cabling-wifi',
            'nav_key' => 'services',
            'template' => 'service',
            'robots' => 'noindex,follow',
            'title' => 'Office Wi-Fi & Network Cabling in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Network cabling and Wi-Fi support for Salt Lake offices that need stable coverage, cleaner infrastructure, and practical remediation.',
            'hero_kicker' => 'Network Cabling & Wi-Fi',
            'hero_title' => 'Office Wi-Fi and Network Cabling',
            'hero_intro' => 'Bald Eagle helps Salt Lake City offices fix weak coverage, messy cabling, and unstable network layouts that slow users down.',
            'card_title' => 'Network Cabling & Wi-Fi',
            'card_copy' => 'Wi-Fi remediation, physical network cleanup, and local office infrastructure work.',
            'pain_points' => [
                'Poor Wi-Fi coverage in critical work areas',
                'Unlabeled or unreliable office cabling',
                'Consumer-grade wireless setups pushed past their limits',
                'Moves, expansions, or layouts that outgrew the original network design',
            ],
            'included' => [
                'Wireless coverage review and remediation planning',
                'Physical network and cabling assessment',
                'Hardware recommendations or implementation support',
                'Cleanup work aligned to office operations and future growth',
            ],
            'who_for_title' => 'For local offices where physical infrastructure is the blocker.',
            'who_for_copy' => 'This service is for Salt Lake businesses dealing with coverage gaps, unstable office connectivity, unmanaged patch panels, or infrastructure that no longer reflects how the space is used.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Unstable office connectivity undermines support tickets, voice quality, cloud access, and general productivity. It also hides larger infrastructure issues.',
                'A cleaner physical network is easier to troubleshoot, easier to secure, and easier to extend when the business changes.',
            ],
            'deliverables' => [
                'Site-specific findings and remediation plan',
                'Coverage or cabling recommendations',
                'Defined scope for corrective project work',
                'Documentation of major infrastructure changes',
            ],
            'cta_title' => 'Need local office network work that gets done cleanly?',
            'cta_copy' => 'Start with the Wi-Fi complaint, office layout issue, or cabling condition that is slowing the team down.',
            'contact_service_type' => 'cabling-wifi',
            'secondary_cta' => ['href' => page_href('one-off-it-projects'), 'label' => 'See project work'],
            'related_links' => ['one-off-it-projects', 'network-security', 'it-services-salt-lake-city'],
        ],
        'network-security' => [
            'slug' => 'network-security',
            'path' => '/network-security',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Scoped Security Hardening in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Scoped security hardening in Salt Lake City for businesses that need better access control, reduced blast radius, and stronger recovery outcomes.',
            'hero_kicker' => 'Security Hardening',
            'hero_title' => 'Scoped Security Hardening',
            'hero_intro' => 'Bald Eagle helps Salt Lake businesses tighten the controls that most affect ransomware resilience, recovery speed, and continuity risk.',
            'card_title' => 'Scoped Security Hardening',
            'card_copy' => 'Targeted hardening for identity, remote access, segmentation, and recovery-critical systems.',
            'pain_points' => [
                'Remote access or identity controls would make a recovery event harder to contain',
                'Flat networks and broad permissions create too much blast radius',
                'Security changes were made reactively and never cleaned up',
                'Critical systems lack the access boundaries needed for credible continuity planning',
            ],
            'included' => [
                'Identity, remote access, and edge control review',
                'Segmentation or trust-boundary recommendations where needed',
                'Scoped corrective hardening aligned to continuity priorities',
                'Recommendations that support backup and recovery outcomes',
            ],
            'who_for_title' => 'For businesses that know their controls are too loose to trust during an incident.',
            'who_for_copy' => 'This service is for companies that need practical hardening to support recovery outcomes, not a broad network security program or enterprise theater.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Small business recovery gets harder when identity, remote access, and internal trust boundaries are loose. Weak controls increase both the chance of compromise and the scope of disruption.',
                'Hardening here is about removing easy mistakes, tightening trust boundaries, and protecting the systems that would matter most during recovery.',
            ],
            'deliverables' => [
                'Current-state hardening review',
                'Prioritized corrective actions',
                'Access, segmentation, or control recommendations',
                'Clear next-step plan for remediation work',
            ],
            'cta_title' => 'Need targeted hardening that supports recovery instead of broad security sprawl?',
            'cta_copy' => 'Start with the access concern, remote entry point, or control gap that would worry you most during an incident.',
            'contact_service_type' => 'network-security',
            'primary_cta_label' => 'Review Ransomware Resilience',
            'process_heading' => 'How targeted hardening work stays tied to resilience instead of bloat.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Assess', 'copy' => 'Identify the identity, remote access, or trust-boundary weakness raising ransomware exposure.'],
                ['step' => '02', 'title' => 'Contain', 'copy' => 'Define the control changes that reduce blast radius without expanding scope into a generic overhaul.'],
                ['step' => '03', 'title' => 'Validate', 'copy' => 'Confirm the hardening actions support backup recovery, continuity, and incident containment goals.'],
            ],
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Request a Risk Assessment'],
            'related_links' => ['security-risk-assessments', 'backup-disaster-recovery', 'managed-it-services'],
        ],
        'one-off-it-projects' => [
            'slug' => 'one-off-it-projects',
            'path' => '/one-off-it-projects',
            'nav_key' => 'projects',
            'template' => 'commercial',
            'robots' => 'noindex,follow',
            'title' => 'One-Off IT Projects in Salt Lake City | Bald Eagle Network Services',
            'description' => 'Remediation projects for Salt Lake businesses with backup/recovery failures, access-control gaps, and focused infrastructure risk.',
            'hero_kicker' => 'Remediation Projects',
            'hero_title' => 'Recovery Remediation Projects',
            'hero_intro' => 'Bald Eagle handles focused remediation projects for Salt Lake City businesses that fail recovery testing or have exposed continuity risks.',
            'card_title' => 'One-Off IT Projects',
            'card_copy' => 'Focused IT and security projects with defined scope, deliverables, and local execution.',
            'pain_points' => [
                'A known technical problem with no one driving it to completion',
                'Project work stalled between vendors or internal staff',
                'Security or access cleanup that needs a defined owner',
                'Infrastructure changes that require local technical execution',
            ],
            'included' => [
                'Project scoping and technical review',
                'Defined deliverables and implementation path',
                'Execution support for local office or cloud changes',
                'Closure notes and recommendations for ongoing support if needed',
            ],
            'who_for_title' => 'For businesses with a specific outcome in mind.',
            'who_for_copy' => 'This service fits companies that have a concrete problem or project goal and need a competent local partner to complete the work without expanding it into a bloated engagement.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Focused projects let the business solve the immediate technical issue without pretending every need requires a long-term contract.',
                'Done well, project work also reveals whether the business would benefit from ongoing support once the urgent problem is resolved.',
            ],
            'deliverables' => [
                'Defined project scope and next steps',
                'Technical execution aligned to the stated outcome',
                'Documented deliverables at completion',
                'Recommendation on whether follow-on support is warranted',
            ],
            'cta_title' => 'Failed the recovery test and need fixes completed cleanly?',
            'cta_copy' => 'Start with the failed checkpoint, timeline, and the business risk if remediation slips again.',
            'contact_service_type' => 'one-off-project',
            'secondary_cta' => ['href' => page_href('security-risk-assessments'), 'label' => 'Run a Recovery Readiness Test'],
            'related_links' => ['network-cabling-wifi', 'backup-disaster-recovery', 'microsoft-365-services'],
        ],
        'privacy-policy' => [
            'slug' => 'privacy-policy',
            'path' => '/privacy-policy',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Privacy Policy | Bald Eagle Network Services',
            'description' => 'Privacy policy for the Bald Eagle Network Services public website and contact request form.',
            'hero_kicker' => 'Privacy Policy',
            'hero_title' => 'How contact requests and site data are handled.',
            'hero_intro' => 'This privacy policy applies to the public website for Bald Eagle Network Services and explains the limited data collected through contact requests.',
            'sections' => [
                [
                    'title' => 'Information Collected',
                    'paragraphs' => [
                        'The public website collects the information you submit through the contact form, including name, company, email address, phone number, preferred contact method, employee count, main concern, assessment type, and message content.',
                        'Basic technical request information such as IP address and browser user agent may also be logged for security, abuse prevention, and troubleshooting.',
                    ],
                ],
                [
                    'title' => 'How Information Is Used',
                    'paragraphs' => [
                        'Submitted information is used to review service fit, respond to inquiries, and manage follow-up related to recovery testing, continuity monitoring, remediation projects, or related support requests.',
                        'Information is not sold or rented through the public website.',
                    ],
                ],
                [
                    'title' => 'Security and Retention',
                    'paragraphs' => [
                        'Reasonable administrative and technical safeguards are used on the public website, including CSRF protection, validation, and anti-abuse controls on the contact form.',
                        'Inquiry data is retained only as long as needed for business communication, recordkeeping, and security review.',
                    ],
                ],
                [
                    'title' => 'Contact',
                    'paragraphs' => [
                        'Questions about this privacy policy can be submitted through the public contact form.',
                    ],
                ],
            ],
        ],
        'security-risk-assessments' => [
            'slug' => 'security-risk-assessments',
            'path' => '/security-risk-assessments',
            'nav_key' => 'services',
            'template' => 'service',
            'title' => 'Cybersecurity Risk Assessment & Recovery Readiness Test | Salt Lake City | Bald Eagle',
            'description' => 'Request a recovery-focused cybersecurity risk assessment in the Salt Lake metro. Get verified findings on restore risk, access-control gaps, and ransomware resilience.',
            'hero_kicker' => 'Recovery Readiness Test',
            'hero_title' => 'Run a Recovery Readiness Test',
            'hero_intro' => 'This assessment gives small Salt Lake businesses a direct view of downtime exposure, backup recoverability, account-access risk, and ransomware readiness.',
            'card_title' => 'Recovery Readiness Test',
            'card_copy' => 'Assessment-first review of recovery readiness, backup restore testing, account-access controls, and ransomware resilience.',
            'pain_points' => [
                'Backups are in place but restore success has not been verified',
                'Account access permissions are hard to explain or defend',
                'Ransomware concern is rising without a clear containment and recovery plan',
                'Downtime risk exists but no one has a prioritized action list',
            ],
            'included' => [
                'Current-state review of recovery, access, and control dependencies',
                'Backup validation and restore testing priorities',
                'Business-risk ranking for corrective actions',
                'Defined next-step scope for remediation and monitoring',
            ],
            'who_for_title' => 'For owner-led businesses that need facts before making changes.',
            'who_for_copy' => 'Best fit is local businesses with 5-20 users in dental, legal, construction, and professional service offices across the Salt Lake metro.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Without assessment data, teams guess at priorities and often spend budget on low-impact changes while major recovery gaps remain open.',
                'A direct assessment creates operational clarity: what must be fixed now, what can wait, and what should be tested to prove recoverability.',
            ],
            'deliverables' => [
                'Written findings with severity and business impact',
                'Prioritized corrective action list',
                'Recovery and restore-testing recommendations',
                'Defined project and monitoring next steps',
            ],
            'assessment_checks' => [
                'Backup coverage and restore-testing status for critical systems',
                'Identity controls, MFA posture, and admin boundaries',
                'Ransomware exposure points across remote access and trust boundaries',
                'Business continuity dependencies and recovery sequence gaps',
            ],
            'assessment_outputs' => [
                'One-page executive risk summary for owners',
                'Technical findings list with severity and business impact',
                '30/60/90-day action plan with defined scope',
                'Recommendation for follow-on remediation or continuity monitoring',
            ],
            'assessment_findings' => [
                [
                    'title' => 'Sample finding: restore failure risk',
                    'copy' => 'Daily backups existed, but no documented test restore had been run for line-of-business data in the prior 12 months.',
                ],
                [
                    'title' => 'Sample finding: account overexposure',
                    'copy' => 'Shared admin credentials and legacy MFA exceptions increased takeover and lateral movement risk.',
                ],
                [
                    'title' => 'Sample finding: undefined recovery order',
                    'copy' => 'No documented order for restoring file shares, line-of-business apps, and user access during outage response.',
                ],
                [
                    'title' => 'Case snapshot: 12-user office',
                    'copy' => 'Assessment identified untested backup sets and broad admin rights; after scoped remediation, restore test passed and admin roles were reduced.',
                ],
            ],
            'assessment_explanation' => [
                'Backups are only one piece of recovery. If restore testing is not current, recovery time and data integrity are assumptions.',
                'Verified recovery means proving that critical systems, permissions, and data can be restored in the order operations require.',
                'Assessment work identifies where backup validation and restore testing must happen first to prevent extended downtime.',
            ],
            'assessment_pricing' => [
                'title' => 'Assessment value: $500, waived for qualified local businesses.',
                'copy' => 'Qualified businesses in Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan may have the fee waived.',
            ],
            'cta_title' => 'Need a direct read on recovery risk before the next disruption?',
            'cta_copy' => 'Run the test and get a clear risk map, prioritized findings, and an execution path.',
            'contact_service_type' => 'risk-assessment',
            'primary_cta_label' => 'Request a Risk Assessment',
            'process_heading' => 'How the assessment moves from uncertainty to a real action plan.',
            'process_steps' => [
                ['step' => '01', 'title' => 'Discover', 'copy' => 'Review the systems, access points, and backup assumptions that matter most to business continuity.'],
                ['step' => '02', 'title' => 'Test', 'copy' => 'Check restore readiness, ransomware exposure, and recovery blockers against the real operating environment.'],
                ['step' => '03', 'title' => 'Report', 'copy' => 'Return prioritized findings, business impact, and the next remediation or monitoring path.'],
            ],
            'show_inline_form' => true,
            'secondary_cta' => ['href' => page_href('contact') . '?service=backup-dr', 'label' => 'Check Backup Readiness'],
            'related_links' => ['network-security', 'managed-it-services', 'backup-disaster-recovery'],
        ],
        'service-area' => [
            'slug' => 'service-area',
            'path' => '/service-area',
            'nav_key' => 'service-area',
            'template' => 'service-area',
            'title' => 'Salt Lake Metro Service Area | Bald Eagle Network Services',
            'description' => 'Bald Eagle serves Salt Lake City metro businesses including West Jordan, Sandy, Draper, Murray, and South Jordan for assessment-led recovery and security work.',
            'hero_kicker' => 'Service Area',
            'hero_title' => 'Salt Lake City Service Area',
            'hero_intro' => 'Bald Eagle serves the Salt Lake metro so on-site recovery work, restore testing, and follow-through stay realistic and accountable.',
            'coverage_points' => [
                'Salt Lake City, West Jordan, Sandy, Draper, Murray, and South Jordan',
                'Typical operating radius of roughly 30 miles',
                'Focused on local offices with 5-20 users',
                'On-site work scheduled around operational windows and business impact',
            ],
            'why_local' => [
                'Travel remains predictable for restore validation and response work',
                'Scope stays grounded in what can actually be delivered on-site',
                'Business owners have direct local accountability, not remote queue handoff',
                'Coverage claims match real operational radius',
            ],
            'local_cards' => [
                ['title' => 'Backup & Recovery', 'copy' => 'For local teams that need verified backups, monitored recovery concerns, and clearer restore expectations.', 'href' => page_href('backup-disaster-recovery')],
                ['title' => 'Recovery Assurance', 'copy' => 'For businesses that need continuity priorities, dependency review, and a more realistic incident recovery plan.', 'href' => page_href('managed-it-services')],
                ['title' => 'Security Assessments', 'copy' => 'For owners who need to understand where ransomware and downtime risk are building before they turn into an incident.', 'href' => page_href('security-risk-assessments')],
                ['title' => 'Scoped Hardening', 'copy' => 'For access, segmentation, and recovery-critical control issues that need correction without expanding into a broad MSP scope.', 'href' => page_href('network-security')],
            ],
        ],
        'services' => [
            'slug' => 'services',
            'path' => '/services',
            'nav_key' => 'services',
            'template' => 'services',
            'title' => 'Cybersecurity, Backup & Recovery Services for Small Businesses | Bald Eagle',
            'description' => 'Small-business cybersecurity, backup verification, recovery planning, and continuity monitoring services for the Salt Lake metro.',
            'hero_kicker' => 'Service Overview',
            'hero_title' => 'What Happens After the Test',
            'hero_intro' => 'Bald Eagle services are organized by test outcomes, not broad MSP categories.',
            'service_cards' => [
                ['title' => 'If You Fail The Test', 'copy' => 'Run a remediation project with defined scope to fix backup restore failure, access-control gaps, and recovery blockers.', 'href' => page_href('one-off-it-projects')],
                ['title' => 'If You Are Exposed', 'copy' => 'Move into a Verified Recovery System with recovery sequencing, restore dependency mapping, and hardening.', 'href' => page_href('managed-it-services')],
                ['title' => 'If You Are Stable', 'copy' => 'Use monthly continuity monitoring to keep verified recovery from drifting back into guesswork.', 'href' => page_href('monthly-it-support-plans')],
                ['title' => 'If Ransomware Risk Is High', 'copy' => 'Apply scoped hardening for remote access, trust boundaries, and blast-radius reduction.', 'href' => page_href('network-security')],
                ['title' => 'Start Here', 'copy' => 'Run the Recovery Readiness Test first. Backups are not recovery until restore testing proves it.', 'href' => page_href('security-risk-assessments')],
            ],
            'approach' => [
                'Run a Recovery Readiness Test to establish facts',
                'If you fail, start a defined remediation project',
                'If you are exposed, deploy a Verified Recovery System',
                'If you are stable, keep monthly continuity monitoring lean and disciplined',
            ],
            'secondary_cta' => ['href' => page_href('backup-disaster-recovery'), 'label' => 'Check Backup Readiness'],
            'final_cta' => [
                'title' => 'Start with the assessment that qualifies the real next step.',
                'copy' => 'The site is designed to move from risk assessment into backup verification, recovery planning, hardening, or continuity monitoring only when the findings support it.',
                'href' => page_href('contact') . '?service=risk-assessment',
                'label' => 'Request a Risk Assessment',
            ],
        ],
        'terms' => [
            'slug' => 'terms',
            'path' => '/terms',
            'nav_key' => '',
            'template' => 'legal',
            'title' => 'Terms of Use | Bald Eagle Network Services',
            'description' => 'Terms of use for the Bald Eagle Network Services public website.',
            'hero_kicker' => 'Terms of Use',
            'hero_title' => 'Terms for use of the public website.',
            'hero_intro' => 'These terms apply to access and use of the Bald Eagle Network Services public website.',
            'sections' => [
                [
                    'title' => 'Website Purpose',
                    'paragraphs' => [
                        'This website provides general information about services offered by Bald Eagle Network Services and a means to submit business inquiries.',
                        'Nothing on the public website guarantees service availability, project acceptance, or a specific business outcome.',
                    ],
                ],
                [
                    'title' => 'Permitted Use',
                    'paragraphs' => [
                        'You may use the website to review services, learn about service area limits, and submit a legitimate business inquiry.',
                        'You may not use the website to interfere with operations, submit abusive traffic, or attempt unauthorized access to any part of the site.',
                    ],
                ],
                [
                    'title' => 'No Client Relationship',
                    'paragraphs' => [
                        'Submitting a form or contacting Bald Eagle Network Services through the website does not by itself create a client relationship, support agreement, or project commitment.',
                        'Any engagement is subject to separate written agreement and scope approval.',
                    ],
                ],
                [
                    'title' => 'Changes',
                    'paragraphs' => [
                        'Website content and these terms may be updated from time to time without prior notice.',
                    ],
                ],
            ],
        ],
        'voip-business-phone-systems' => [
            'slug' => 'voip-business-phone-systems',
            'path' => '/voip-business-phone-systems',
            'nav_key' => 'services',
            'template' => 'service',
            'robots' => 'noindex,follow',
            'title' => 'VoIP Business Phone Systems in Salt Lake City | Bald Eagle Network Services',
            'description' => 'VoIP business phone system support for Salt Lake companies that need better call reliability, cleaner deployment, and network alignment.',
            'hero_kicker' => 'VoIP Business Phone Systems',
            'hero_title' => 'VoIP Phone System Support',
            'hero_intro' => 'Bald Eagle helps Salt Lake City businesses fix call reliability, deployment issues, and network conditions that undermine business phone systems.',
            'card_title' => 'VoIP Business Phone Systems',
            'card_copy' => 'VoIP rollout support, remediation, and network alignment for business calling.',
            'pain_points' => [
                'Poor call quality caused by weak network conditions',
                'Phone platform rollouts with unclear ownership',
                'Desk phone and softphone support issues during office changes',
                'Unreliable voice service during peak business hours',
            ],
            'included' => [
                'VoIP environment review and project scoping',
                'Network readiness evaluation for voice traffic',
                'Deployment or remediation support',
                'Coordination with voice platform vendors when needed',
            ],
            'who_for_title' => 'For businesses that cannot tolerate call instability.',
            'who_for_copy' => 'This service fits offices where phone quality affects sales, operations, or customer responsiveness and the current voice setup is being undermined by design or support gaps.',
            'why_title' => 'Why it matters',
            'why_paragraphs' => [
                'Voice reliability is still operationally critical for many small businesses. When the phone system is unstable, it becomes a customer service problem immediately.',
                'A clean VoIP deployment depends on network health, vendor coordination, and user setup discipline. Ignoring any one of those creates repeat issues.',
            ],
            'deliverables' => [
                'VoIP deployment or remediation plan',
                'Network readiness findings',
                'Platform support coordination notes',
                'Defined next steps for rollout or corrective work',
            ],
            'cta_title' => 'Need a phone system fix without a messy cutover?',
            'cta_copy' => 'Start with the voice issue, current platform, and the office conditions affecting call quality.',
            'contact_service_type' => 'voip',
            'secondary_cta' => ['href' => page_href('network-cabling-wifi'), 'label' => 'See Wi-Fi and cabling work'],
            'related_links' => ['network-cabling-wifi', 'one-off-it-projects', 'managed-it-services'],
        ],
    ];

    return $definitions;
}
