<?php
declare(strict_types=1);

return [
    'cybersecurity-salt-lake-city' => [
        'slug' => 'cybersecurity-salt-lake-city',
        'path' => '/cybersecurity-salt-lake-city',
        'nav_key' => 'services',
        'template' => 'local',
        'robots' => 'noindex,follow',
        'title' => 'Cybersecurity Services in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Ransomware resilience and control hardening in Salt Lake City for small businesses that need practical risk reduction.',
        'hero_kicker' => 'Salt Lake City Cybersecurity',
        'hero_title' => 'Cybersecurity Services in Salt Lake City',
        'hero_intro' => 'Bald Eagle helps Salt Lake City small businesses reduce risk through recovery testing, hardening, backup review, and practical remediation.',
        'card_title' => 'Cybersecurity Salt Lake City',
        'card_copy' => 'Local cybersecurity assessments and remediation for Salt Lake City businesses.',
        'pain_points' => [
            'Security concerns with no practical triage path',
            'Remote access, identity, or backup concerns building over time',
            'Outside pressure from clients, insurers, or leadership',
            'No clear understanding of what needs to be fixed first',
        ],
        'included' => [
            'Risk assessments for local business environments',
            'Network and control remediation guidance',
            'Account access and endpoint issues included where relevant',
            'Practical recommendations aligned to business operations',
        ],
        'who_for_title' => 'For Salt Lake City companies that want clarity on security priorities.',
        'who_for_copy' => 'This page is for owners and managers who know the environment needs stronger controls but do not need generic fear language or enterprise theater.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Security problems tend to be cumulative. Weak identity, unverified backups, broad permissions, and old firewall changes create risk that is hard to see until something goes wrong.',
            'A local review gives the business a clearer path to remediation and a tighter connection between on-site reality and control recommendations.',
        ],
        'deliverables' => [
            'Salt Lake City security review and findings',
            'Prioritized corrective actions',
            'Next-step recommendation for project work or ongoing support',
            'Internal links to related services and assessment pages',
        ],
        'cta_title' => 'Need a cybersecurity review for a Salt Lake City business?',
        'cta_copy' => 'Describe the control concern, business pressure, or recent security issue driving the request.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'endpoint-management' => [
        'slug' => 'endpoint-management',
        'path' => '/endpoint-management',
        'nav_key' => 'services',
        'template' => 'service',
        'robots' => 'noindex,follow',
        'title' => 'Endpoint Management Services in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Endpoint management services in Salt Lake City for small businesses that need stronger device standards, patching discipline, and user workstation control.',
        'hero_kicker' => 'Endpoint Management',
        'hero_title' => 'Endpoint Management for Small Businesses',
        'hero_intro' => 'Bald Eagle helps Salt Lake City businesses standardize devices, improve patching, and reduce recurring support friction tied to weak endpoint control.',
        'card_title' => 'Endpoint Management',
        'card_copy' => 'Device standards, patching discipline, and workstation control for small business teams.',
        'pain_points' => [
            'Workstations configured differently across the company',
            'Weak patch hygiene or no real endpoint owner',
            'Stale devices, uncertain inventory, and poor offboarding',
            'User issues that keep repeating because the endpoint baseline is weak',
        ],
        'included' => [
            'Endpoint review and standards assessment',
            'Patch and device management recommendations',
            'Inventory and lifecycle guidance',
            'Support alignment between devices, account access controls, and security controls',
        ],
        'who_for_title' => 'For businesses whose device baseline is inconsistent.',
        'who_for_copy' => 'This service fits companies that need better visibility and control over user workstations, laptops, and day-to-day device administration.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Weak endpoint discipline creates more tickets, more risk, and more wasted time during onboarding, offboarding, and support.',
            'A stronger endpoint baseline improves security, reduces recurring friction, and makes support faster because the environment is less chaotic.',
        ],
        'deliverables' => [
            'Endpoint posture summary',
            'Standardization and patching recommendations',
            'Prioritized remediation list',
            'Next-step path into managed support if appropriate',
        ],
        'cta_title' => 'Need better control over company devices?',
        'cta_copy' => 'Start with the endpoint issue, patching concern, or user device pattern that keeps resurfacing.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'it-services-salt-lake-city' => [
        'slug' => 'it-services-salt-lake-city',
        'path' => '/it-services-salt-lake-city',
        'nav_key' => 'services',
        'template' => 'local',
        'robots' => 'noindex,follow',
        'title' => 'IT Services in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Recovery-focused IT services in Salt Lake City for small businesses that need dependable support and local execution.',
        'hero_kicker' => 'Salt Lake City IT Services',
        'hero_title' => 'Local IT Services in Salt Lake City',
        'hero_intro' => 'Bald Eagle supports Salt Lake City small businesses that need dependable IT help, recovery discipline, infrastructure cleanup, and direct local accountability.',
        'card_title' => 'IT Services Salt Lake City',
        'card_copy' => 'Local IT support and project work for businesses in Salt Lake City.',
        'pain_points' => [
            'No clear IT owner inside a growing local business',
            'Too much time lost to recurring support issues',
            'Cloud and office systems drifting without oversight',
            'Need for local project execution instead of remote-only advice',
        ],
        'included' => [
            'Monthly support and project work for Salt Lake City offices',
            'Account access and user support tied to recovery outcomes',
            'Endpoint, network, and backup remediation as needed',
            'Local coverage that stays inside a practical radius',
        ],
        'who_for_title' => 'For Salt Lake City businesses that want direct local support.',
        'who_for_copy' => 'This page is aimed at companies operating in Salt Lake City that need a small-business IT partner with a tighter service area and clearer support boundaries than broad regional providers.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Local support matters when offices need on-site remediation, network work, or a real understanding of the business environment instead of purely remote assumptions.',
            'A tighter radius also helps keep response expectations realistic and avoids overselling geography.',
        ],
        'deliverables' => [
            'Local Salt Lake City service review',
            'Support or project fit recommendation',
            'Defined next step for monthly support or scoped remediation',
            'Internal links to service-specific pages',
        ],
        'cta_title' => 'Need local IT support inside Salt Lake City?',
        'cta_copy' => 'Describe the issue, the office setup, and whether you need monthly support or a focused project.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'managed-it-services' => [
        'slug' => 'managed-it-services',
        'path' => '/managed-it-services',
        'nav_key' => 'services',
        'template' => 'service',
        'robots' => 'noindex,follow',
        'title' => 'Recovery Assurance Services in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Recovery Assurance services for Salt Lake metro businesses that need defined restore sequencing, dependency mapping, and verified recovery confidence.',
        'hero_kicker' => 'Recovery Assurance',
        'hero_title' => 'Recovery Assurance for Small Businesses',
        'hero_intro' => 'Bald Eagle helps Salt Lake businesses define what must be restored first, what dependencies are still risky, and what continuity gaps need attention before an incident forces the answer.',
        'card_title' => 'Recovery Assurance',
        'card_copy' => 'Continuity prioritization, dependency review, and recovery planning for small business environments.',
        'pain_points' => [
            'Critical systems have no clear order of recovery',
            'Backups exist but no one has mapped the real business dependencies',
            'Owners are unsure how long the business could operate during an outage',
            'Response plans rely on tribal knowledge instead of tested recovery steps',
        ],
        'included' => [
            'Business continuity and dependency review',
            'Recovery sequencing for critical systems and workflows',
            'Identification of restore blockers and recovery assumptions',
            'Recommendations for follow-up verification or scoped hardening',
        ],
        'who_for_title' => 'Built for owner-led teams without internal continuity depth.',
        'who_for_copy' => 'This service fits small professional-service businesses and offices that cannot afford guesswork during an outage and need a more credible continuity posture.',
        'why_title' => 'Why recovery readiness matters',
        'why_paragraphs' => [
            'When recovery decisions are improvised, downtime stretches and owners find out too late which assumptions were wrong.',
            'A readiness review creates a more realistic path to continuity because it connects business priorities, systems, and restore expectations before an incident occurs.',
        ],
        'deliverables' => [
            'Recovery readiness summary',
            'Priority sequence for critical systems and workflows',
            'List of restore blockers or continuity gaps',
            'Clear next-step plan for testing, hardening, or ongoing monitoring',
        ],
        'cta_title' => 'Need a clearer recovery plan before the next outage or ransomware event?',
        'cta_copy' => 'Start with the system, workflow, or unanswered recovery question that would hurt the business most if it failed.',
        'contact_service_type' => 'monthly-backup-verification',
        'primary_cta_label' => 'Request a Recovery Assessment',
        'process_heading' => 'How a recovery planning engagement is structured.',
        'process_steps' => [
            ['step' => '01', 'title' => 'Scope', 'copy' => 'Define the systems, workflows, and downtime assumptions that deserve immediate attention.'],
            ['step' => '02', 'title' => 'Sequence', 'copy' => 'Map the restore order, dependencies, and blockers that would slow a real recovery.'],
            ['step' => '03', 'title' => 'Document', 'copy' => 'Turn the findings into a practical recovery plan with clear next actions.'],
        ],
        'secondary_cta' => ['href' => '/monthly-it-support-plans', 'label' => 'See Monthly Backup Verification'],
        'related_links' => [],
    ],
    'managed-it-support-salt-lake-city' => [
        'slug' => 'managed-it-support-salt-lake-city',
        'path' => '/managed-it-support-salt-lake-city',
        'nav_key' => 'plans',
        'template' => 'local',
        'robots' => 'noindex,follow',
        'title' => 'Managed IT Support in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Continuity monitoring in Salt Lake City for small businesses that need monthly recovery oversight and local accountability.',
        'hero_kicker' => 'Salt Lake City Continuity Monitoring',
        'hero_title' => 'Continuity Monitoring in Salt Lake City',
        'hero_intro' => 'This local page is for Salt Lake City businesses that need monthly recovery oversight, stronger standards, and a nearby operating partner.',
        'card_title' => 'Managed IT Support Salt Lake City',
        'card_copy' => 'Monthly support coverage for Salt Lake City businesses needing steadier IT ownership.',
        'pain_points' => [
            'Unclear ownership of daily support and environment hygiene',
            'Recurring user issues interrupting small teams',
            'Devices and account access controls drifting over time',
            'Need for a local partner with realistic on-site coverage',
        ],
        'included' => [
            'Monthly support structure for local businesses',
            'User support, device oversight, and account-access administration',
            'Security-minded recommendations as part of routine service',
            'Escalation into project work when bigger changes are needed',
        ],
        'who_for_title' => 'For Salt Lake City businesses past the ad hoc stage.',
        'who_for_copy' => 'This page is for companies that have outgrown informal tech support and need a more structured monthly relationship without hiring full internal IT staff.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Managed support creates consistency across support requests, device management, access control, and small ongoing improvements.',
            'That consistency is usually the difference between a business that is constantly reacting and one that can plan around its technology.',
        ],
        'deliverables' => [
            'Managed support fit review for Salt Lake City operations',
            'Defined monthly coverage recommendation',
            'Initial priority list for stability and security work',
            'Direct path into engagement planning',
        ],
        'cta_title' => 'Need continuity monitoring in Salt Lake City without bloated MSP packaging?',
        'cta_copy' => 'Send the current headcount, office location, and the support pattern that is creating the most drag.',
        'contact_service_type' => 'monthly-backup-verification',
        'secondary_cta' => ['href' => '/monthly-it-support-plans', 'label' => 'See Monthly Backup Verification'],
        'related_links' => [],
    ],
    'microsoft-365-services' => [
        'slug' => 'microsoft-365-services',
        'path' => '/microsoft-365-services',
        'nav_key' => 'services',
        'template' => 'service',
        'robots' => 'noindex,follow',
        'title' => 'Identity & Access Recovery Controls in Salt Lake City | Bald Eagle',
        'description' => 'Identity and access control services in Salt Lake City for small businesses that need account recovery discipline tied to continuity outcomes.',
        'hero_kicker' => 'Identity & Access Review',
        'hero_title' => 'Identity and Access Controls for Recovery-Critical Workflows',
        'hero_intro' => 'Bald Eagle helps Salt Lake City small businesses control account access, identity, permissions, and day-to-day admin drift that slows recovery.',
        'card_title' => 'Identity & Access Review',
        'card_copy' => 'Account administration, identity controls, access discipline, and user support tied to continuity.',
        'pain_points' => [
            'Users, groups, and licenses that no longer reflect reality',
            'Weak MFA or identity settings around sensitive access',
            'Mailbox, SharePoint, and Teams permissions with too much spread',
            'No one clearly responsible for access hygiene',
        ],
        'included' => [
            'Account administration and access support',
            'Identity, MFA, and access policy review',
            'Email and file access operational support',
            'Corrective security and cleanup work tied to business use',
        ],
        'who_for_title' => 'For companies depending on account access every day.',
        'who_for_copy' => 'This service fits businesses where email, collaboration, identity, and file access all run through cloud accounts and weak administration is starting to show up as risk or inefficiency.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Poor account administration creates more than user frustration. It creates over-permissioned access, weak offboarding, and uneven protection around business-critical data.',
            'A clean access environment is easier to support, easier to secure, and easier to explain when an owner needs to understand risk.',
        ],
        'deliverables' => [
            'Identity and access support and cleanup plan',
            'Administrative corrections or recommendations',
            'Identity and access review outcomes',
            'Defined next steps for deeper security or compliance work',
        ],
        'cta_title' => 'Need identity and access support that goes beyond password resets?',
        'cta_copy' => 'Start with the account-access issue or cleanup project that needs a clear owner.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'microsoft-365-support-salt-lake-city' => [
        'slug' => 'microsoft-365-support-salt-lake-city',
        'path' => '/microsoft-365-support-salt-lake-city',
        'nav_key' => 'services',
        'template' => 'local',
        'robots' => 'noindex,follow',
        'title' => 'Account Access Support in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Account access support in Salt Lake City for small businesses that need identity controls and practical administration.',
        'hero_kicker' => 'Salt Lake City Account Access Support',
        'hero_title' => 'Account Access Support in Salt Lake City',
        'hero_intro' => 'This local page is for Salt Lake City businesses that need access cleanup, identity control, and practical account administration.',
        'card_title' => 'Account Access Support Salt Lake City',
        'card_copy' => 'Local account-access support for identity, permissions, and administration cleanup.',
        'pain_points' => [
            'Access sprawl caused by years of unchecked changes',
            'Licensing and user access not matching current staff',
            'Email and file-access settings with weak ownership',
            'Need for local support tied to business operations',
        ],
        'included' => [
            'Access administration and cleanup guidance',
            'Identity and MFA control review',
            'User support and account access issue resolution',
            'Recommendations linked to broader managed support if needed',
        ],
        'who_for_title' => 'For Salt Lake City companies leaning heavily on cloud account access.',
        'who_for_copy' => 'This page is meant for businesses where cloud identity and file access run daily operations and the access model now needs deliberate administration.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Small access mistakes compound over time. Weak offboarding, stale accounts, broad permissions, and inconsistent MFA all add operational and security risk.',
            'A cleaner access model is easier for users, easier to manage, and easier to defend when outside requirements increase.',
        ],
        'deliverables' => [
            'Salt Lake City account-access support review',
            'Access cleanup and control recommendations',
            'Defined support path for administration or remediation',
            'Internal links to related security and support services',
        ],
        'cta_title' => 'Need Salt Lake City account-access support with tighter control?',
        'cta_copy' => 'Send the access issue, current headcount, and the area causing the most friction.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'network-cabling-wifi' => [
        'slug' => 'network-cabling-wifi',
        'path' => '/network-cabling-wifi',
        'nav_key' => 'services',
        'template' => 'service',
        'robots' => 'noindex,follow',
        'title' => 'Office Wi-Fi & Network Cabling in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Network cabling and Wi-Fi support for Salt Lake offices that need stable coverage, cleaner infrastructure, and practical remediation.',
        'hero_kicker' => 'Network Cabling & Wi-Fi',
        'hero_title' => 'Office Wi-Fi and Network Cabling',
        'hero_intro' => 'Bald Eagle helps Salt Lake City offices fix weak coverage, messy cabling, and unstable network layouts that slow users down.',
        'card_title' => 'Network Cabling & Wi-Fi',
        'card_copy' => 'Wi-Fi remediation, physical network cleanup, and local office infrastructure work.',
        'pain_points' => [
            'Poor Wi-Fi coverage in critical work areas',
            'Unlabeled or unreliable office cabling',
            'Consumer-grade wireless setups pushed past their limits',
            'Moves, expansions, or layouts that outgrew the original network design',
        ],
        'included' => [
            'Wireless coverage review and remediation planning',
            'Physical network and cabling assessment',
            'Hardware recommendations or implementation support',
            'Cleanup work aligned to office operations and future growth',
        ],
        'who_for_title' => 'For local offices where physical infrastructure is the blocker.',
        'who_for_copy' => 'This service is for Salt Lake businesses dealing with coverage gaps, unstable office connectivity, unmanaged patch panels, or infrastructure that no longer reflects how the space is used.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Unstable office connectivity undermines support tickets, voice quality, cloud access, and general productivity. It also hides larger infrastructure issues.',
            'A cleaner physical network is easier to troubleshoot, easier to secure, and easier to extend when the business changes.',
        ],
        'deliverables' => [
            'Site-specific findings and remediation plan',
            'Coverage or cabling recommendations',
            'Defined scope for corrective project work',
            'Documentation of major infrastructure changes',
        ],
        'cta_title' => 'Need local office network work that gets done cleanly?',
        'cta_copy' => 'Start with the Wi-Fi complaint, office layout issue, or cabling condition that is slowing the team down.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'one-off-it-projects' => [
        'slug' => 'one-off-it-projects',
        'path' => '/one-off-it-projects',
        'nav_key' => 'projects',
        'template' => 'commercial',
        'robots' => 'noindex,follow',
        'title' => 'One-Off IT Projects in Salt Lake City | Bald Eagle Network Services',
        'description' => 'Remediation projects for Salt Lake businesses with backup/recovery failures, access-control gaps, and focused infrastructure risk.',
        'hero_kicker' => 'Remediation Projects',
        'hero_title' => 'Recovery Remediation Projects',
        'hero_intro' => 'Bald Eagle handles focused remediation projects for Salt Lake City businesses that fail recovery testing or have exposed continuity risks.',
        'card_title' => 'One-Off IT Projects',
        'card_copy' => 'Focused IT and security projects with defined scope, deliverables, and local execution.',
        'pain_points' => [
            'A known technical problem with no one driving it to completion',
            'Project work stalled between vendors or internal staff',
            'Security or access cleanup that needs a defined owner',
            'Infrastructure changes that require local technical execution',
        ],
        'included' => [
            'Project scoping and technical review',
            'Defined deliverables and implementation path',
            'Execution support for local office or cloud changes',
            'Closure notes and recommendations for ongoing support if needed',
        ],
        'who_for_title' => 'For businesses with a specific outcome in mind.',
        'who_for_copy' => 'This service fits companies that have a concrete problem or project goal and need a competent local partner to complete the work without expanding it into a bloated engagement.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Focused projects let the business solve the immediate technical issue without pretending every need requires a long-term contract.',
            'Done well, project work also reveals whether the business would benefit from ongoing support once the urgent problem is resolved.',
        ],
        'deliverables' => [
            'Defined project scope and next steps',
            'Technical execution aligned to the stated outcome',
            'Documented deliverables at completion',
            'Recommendation on whether follow-on support is warranted',
        ],
        'cta_title' => 'Failed the recovery test and need fixes completed cleanly?',
        'cta_copy' => 'Start with the failed checkpoint, timeline, and the business risk if remediation slips again.',
        'contact_service_type' => 'risk-assessment',
        'secondary_cta' => ['href' => '/recovery-assessment', 'label' => 'Start a Recovery Assessment'],
        'related_links' => [],
    ],
    'voip-business-phone-systems' => [
        'slug' => 'voip-business-phone-systems',
        'path' => '/voip-business-phone-systems',
        'nav_key' => 'services',
        'template' => 'service',
        'robots' => 'noindex,follow',
        'title' => 'VoIP Business Phone Systems in Salt Lake City | Bald Eagle Network Services',
        'description' => 'VoIP business phone system support for Salt Lake companies that need better call reliability, cleaner deployment, and network alignment.',
        'hero_kicker' => 'VoIP Business Phone Systems',
        'hero_title' => 'VoIP Phone System Support',
        'hero_intro' => 'Bald Eagle helps Salt Lake City businesses fix call reliability, deployment issues, and network conditions that undermine business phone systems.',
        'card_title' => 'VoIP Business Phone Systems',
        'card_copy' => 'VoIP rollout support, remediation, and network alignment for business calling.',
        'pain_points' => [
            'Poor call quality caused by weak network conditions',
            'Phone platform rollouts with unclear ownership',
            'Desk phone and softphone support issues during office changes',
            'Unreliable voice service during peak business hours',
        ],
        'included' => [
            'VoIP environment review and project scoping',
            'Network readiness evaluation for voice traffic',
            'Deployment or remediation support',
            'Coordination with voice platform vendors when needed',
        ],
        'who_for_title' => 'For businesses that cannot tolerate call instability.',
        'who_for_copy' => 'This service fits offices where phone quality affects sales, operations, or customer responsiveness and the current voice setup is being undermined by design or support gaps.',
        'why_title' => 'Why it matters',
        'why_paragraphs' => [
            'Voice reliability is still operationally critical for many small businesses. When the phone system is unstable, it becomes a customer service problem immediately.',
            'A clean VoIP deployment depends on network health, vendor coordination, and user setup discipline. Ignoring any one of those creates repeat issues.',
        ],
        'deliverables' => [
            'VoIP deployment or remediation plan',
            'Network readiness findings',
            'Platform support coordination notes',
            'Defined next steps for rollout or corrective work',
        ],
        'cta_title' => 'When voice fails, the business still has to answer.',
        'cta_copy' => 'Bring the cutover risk, call failure, or network condition dragging call quality down.',
        'contact_service_type' => 'other',
        'secondary_cta' => ['href' => '/contact', 'label' => 'Contact Bald Eagle'],
        'related_links' => [],
    ],
];
